# generated by datamodel-codegen:
#   timestamp: 2022-09-15T02:18:15+00:00


from __future__ import annotations

from typing import Any

from melanie import BaseModel, Field


class HttpHeaders(BaseModel):
    user__agent: str | None = Field(None, alias="User-Agent")
    accept: str | None = Field(None, alias="Accept")
    accept__language: str | None = Field(None, alias="Accept-Language")
    sec__fetch__mode: str | None = Field(None, alias="Sec-Fetch-Mode")
    cookie: str | None = Field(None, alias="Cookie")


class Format(BaseModel):
    url: str | None
    filesize: int | None
    ext: str | None
    acodec: str | None
    source_preference: int | None
    format_id: str | None
    format_note: str | None = ""
    vcodec: str | None
    width: int | None
    height: int | None
    preference: int | None
    protocol: str | None
    video_ext: str | None
    audio_ext: str | None
    format: str | None
    resolution: str | None
    dynamic_range: str | None
    http_headers: HttpHeaders | None
    tbr: int | None
    fps: Any | None
    quality: int | None
    vbr: int | None
    abr: int | None


class Thumbnail(BaseModel):
    id: str | None
    url: str | None


class _Version(BaseModel):
    version: str | None
    current_git_head: Any | None
    release_git_head: str | None
    repository: str | None


class RequestedDownload(BaseModel):
    url: str | None
    filesize: int | None
    ext: str | None
    acodec: str | None
    source_preference: int | None
    format_id: str | None
    format_note: str | None
    vcodec: str | None
    width: int | None
    height: int | None
    tbr: int | None
    quality: int | None
    protocol: str | None
    video_ext: str | None
    audio_ext: str | None
    vbr: int | None
    abr: int | None
    format: str | None
    resolution: str | None
    dynamic_range: str | None
    http_headers: HttpHeaders | None
    epoch: int | None
    infojson_filename: str | None
    filepath: str | None


class TiktokYoutubeDLResult(BaseModel):
    id: str | None
    extractor_key: str | None
    extractor: str | None
    webpage_url: str | None
    title: str | None
    description: str | None
    view_count: int | None
    like_count: int | None
    repost_count: int | None
    comment_count: int | None
    uploader: str | None
    creator: str | None
    uploader_id: str | None
    uploader_url: str | None
    track: str | None
    album: Any | None
    artist: str | None
    timestamp: int | None
    formats: list[Format] | None
    subtitles: dict[str, Any] | None
    thumbnails: list[Thumbnail] | None
    duration: int | None
    availability: Any | None
    original_url: str | None
    webpage_url_basename: str | None
    webpage_url_domain: str | None
    playlist: Any | None
    playlist_index: Any | None
    thumbnail: str | None
    display_id: str | None
    fulltitle: str | None
    duration_string: str | None
    upload_date: str | None
    requested_subtitles: Any | None
    _has_drm: Any | None
    requested_downloads: list[RequestedDownload] | None
    url: str | None
    filesize: int | None
    ext: str | None
    acodec: str | None
    source_preference: int | None
    format_id: str | None
    format_note: str | None
    vcodec: str | None
    width: int | None
    height: int | None
    tbr: int | None
    quality: int | None
    protocol: str | None
    video_ext: str | None
    audio_ext: str | None
    vbr: int | None
    abr: int | None
    format: str | None
    resolution: str | None
    dynamic_range: str | None
    http_headers: HttpHeaders | None

    @property
    def download(self) -> RequestedDownload:
        return self.requested_downloads[0]
