from __future__ import annotations

from datetime import datetime  # noqa
from typing import Any

from melanie import Field

from .base import BaseModel


class BitcoinTransactionResponse(BaseModel):
    txid: str | None
    updated_at: float | None
    confirmations: str | None
    fee_rate: str | None
    fee: str | None
    features: str | None = Field(None, description="Features added and omitted from the transaction")
    timestamp: str | None
    size: str | None
    weight: str | None
    virtual_size: str | None
    version: str | None
    locktime: str | None
    total_value: str | None = Field(None, description="Total value of the transaction")
    eta: str | None
    current_btc_market_rate: str | None
    usd_value: str | None


# generated by datamodel-codegen:
#   timestamp: 2023-03-25T00:30:41+00:00


class Usd(BaseModel):
    price: float | None
    volume_24h: float | None
    volume_change_24h: float | None
    percent_change_1h: float | None
    percent_change_24h: float | None
    percent_change_7d: float | None
    percent_change_30d: float | None
    percent_change_60d: float | None
    percent_change_90d: float | None
    market_cap: float | None
    market_cap_dominance: float | None
    fully_diluted_market_cap: float | None
    tvl: Any | None
    last_updated: datetime | None


class Status(BaseModel):
    timestamp: datetime | None
    error_code: int | None
    error_message: Any | None
    elapsed: int | None
    credit_count: int | None
    notice: Any | None


class Quote(BaseModel):
    usd: Usd | None = Field(None, alias="USD")


class Field1(BaseModel):
    id: int | None
    name: str | None
    symbol: str | None
    slug: str | None
    num_market_pairs: int | None
    date_added: datetime | None
    tags: list[str] | None
    max_supply: int | None
    circulating_supply: int | None
    total_supply: int | None
    is_active: int | None
    platform: Any | None
    cmc_rank: int | None
    is_fiat: int | None
    self_reported_circulating_supply: Any | None
    self_reported_market_cap: Any | None
    tvl_ratio: Any | None
    last_updated: datetime | None
    quote: Quote | None


class Data(BaseModel):
    field_1: Field1 | None = Field(None, alias="1")


class BtcPriceRawResponse(BaseModel):
    status: Status | None
    data: Data | None
