# generated by datamodel-codegen:
#   timestamp: 2023-02-18T23:17:49+00:00

from __future__ import annotations

from typing import Optional

from melanie import BaseModel


class Meta(BaseModel):
    cached_at: Optional[int]


class Player(BaseModel):
    meta: Optional[Meta]
    username: Optional[str]
    id: Optional[str]
    raw_id: Optional[str]
    avatar: Optional[str]
    name_history: Optional[list]


class Data(BaseModel):
    player: Optional[Player]


class MinecraftUUIDLookupResonse(BaseModel):
    code: Optional[str]
    message: Optional[str]
    data: Optional[Data]
    success: Optional[bool]
