# generated by datamodel-codegen:
#   timestamp: 2023-10-05T16:42:43+00:00

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Optional

from melanie import AnyUrl, BaseModel, Field


class AggregateRating(BaseModel):
    id: Optional[str]
    name: Optional[Any]
    rating_distribution: Optional[List]
    rating_value: Optional[str]
    type: Optional[str]


class AggregatedStats(BaseModel):
    done: Optional[int]
    saves: Optional[int]


class AnalysisUa(BaseModel):
    app_type: Optional[int]
    browser_name: Optional[str]
    browser_version: Optional[str]
    device: Optional[str]
    device_type: Optional[Any]
    os_name: Optional[str]
    os_version: Optional[str]


class FaviconImages(BaseModel):
    orig: Optional[AnyUrl]


class Image(BaseModel):
    height: Optional[int]
    url: Optional[AnyUrl]
    width: Optional[int]


class OfferSummary(BaseModel):
    availability: Optional[int]
    currency: Optional[str]
    in_stock: Optional[bool]
    price: Optional[str]
    price_val: Optional[float]


class Options(BaseModel):
    bookmarks: Optional[List[str]]
    field_set_key: Optional[str]
    id: Optional[str]


class RecommendScore(BaseModel):
    count: Optional[int]
    score: Optional[float]


class Resource(BaseModel):
    name: Optional[str]
    options: Optional[Options]


class VerifiedIdentity(BaseModel):
    pass


class Field736X(BaseModel):
    canonical_image: Optional[Image]
    image_signature: Optional[str]


class AdditionalImagesPerSpec(BaseModel):
    field_736x: Annotated[Optional[List[Field736X]], Field(alias="736x")]


class CanonicalImages(BaseModel):
    field_736x: Annotated[Optional[Image], Field(alias="736x")]


class CloseupAttribution(BaseModel):
    ads_only_profile_site: Optional[Any]
    blocked_by_me: Optional[bool]
    domain_url: Optional[str]
    domain_verified: Optional[bool]
    explicitly_followed_by_me: Optional[bool]
    first_name: Optional[str]
    followed_by_me: Optional[bool]
    follower_count: Optional[int]
    full_name: Optional[str]
    id: Optional[str]
    image_medium_url: Optional[AnyUrl]
    image_small_url: Optional[AnyUrl]
    indexed: Optional[bool]
    is_ads_only_profile: Optional[bool]
    is_default_image: Optional[bool]
    is_verified_merchant: Optional[bool]
    type: Optional[str]
    username: Optional[str]
    verified_identity: Optional[VerifiedIdentity]


class DidItData(BaseModel):
    details_count: Optional[int]
    images_count: Optional[int]
    rating: Optional[int]
    recommend_scores: Optional[List[RecommendScore]]
    recommended_count: Optional[int]
    responses_count: Optional[int]
    tags: Optional[List]
    type: Optional[str]
    user_count: Optional[int]
    videos_count: Optional[int]


class LinkDomain(BaseModel):
    official_user: Optional[CloseupAttribution]


class User(BaseModel):
    ads_only_profile_site: Optional[Any]
    age_in_years: Optional[int]
    allow_analytic_cookies: Optional[Any]
    allow_marketing_cookies: Optional[Any]
    allow_personalization_cookies: Optional[Any]
    can_enable_mfa: Optional[bool]
    connected_to_dropbox: Optional[bool]
    connected_to_etsy: Optional[bool]
    connected_to_facebook: Optional[bool]
    connected_to_google: Optional[bool]
    connected_to_instagram: Optional[bool]
    connected_to_microsoft: Optional[bool]
    connected_to_youtube: Optional[bool]
    country: Optional[str]
    created_at: Optional[str]
    custom_gender: Optional[Any]
    domain_url: Optional[Any]
    domain_verified: Optional[bool]
    email: Optional[str]
    epik: Optional[str]
    facebook_id: Optional[str]
    facebook_publish_stream_enabled: Optional[bool]
    facebook_timeline_enabled: Optional[bool]
    first_name: Optional[str]
    full_name: Optional[str]
    gender: Optional[str]
    gplus_url: Optional[AnyUrl]
    has_mfa_enabled: Optional[bool]
    has_password: Optional[bool]
    has_quicksave_board: Optional[bool]
    id: Optional[str]
    image_large_url: Optional[AnyUrl]
    image_medium_url: Optional[AnyUrl]
    image_small_url: Optional[AnyUrl]
    image_xlarge_url: Optional[AnyUrl]
    ip_country: Optional[str]
    ip_region: Optional[str]
    is_ads_only_profile: Optional[bool]
    is_any_website_verified: Optional[bool]
    is_candidate_for_parental_control_passcode: Optional[bool]
    is_eligible_for_image_only_grid: Optional[bool]
    is_employee: Optional[bool]
    is_high_risk: Optional[bool]
    is_matured_new_user: Optional[bool]
    is_parental_control_passcode_enabled: Optional[bool]
    is_partner: Optional[bool]
    is_private_profile: Optional[bool]
    is_under_16: Optional[bool]
    is_under_18: Optional[bool]
    is_write_banned: Optional[bool]
    last_name: Optional[str]
    listed_website_url: Optional[Any]
    login_state: Optional[int]
    nags: Optional[List]
    parental_control_anonymized_email: Optional[Any]
    partner: Optional[Any]
    personalize_from_offsite_browsing: Optional[bool]
    phone_country: Optional[Any]
    phone_number: Optional[Any]
    phone_number_end: Optional[str]
    profile_discovered_public: Optional[Any]
    push_package_user_id: Optional[str]
    resurrection_info: Optional[Any]
    should_show_messaging: Optional[bool]
    show_personal_boutique: Optional[bool]
    third_party_marketing_tracking_enabled: Optional[bool]
    twitter_publish_enabled: Optional[bool]
    twitter_url: Optional[Any]
    type: Optional[str]
    unverified_phone_country: Optional[Any]
    unverified_phone_number: Optional[Any]
    unverified_phone_number_without_country: Optional[str]
    username: Optional[str]
    verified_domains: Optional[List]
    verified_identity: Optional[VerifiedIdentity]
    verified_user_websites: Optional[List]
    website_url: Optional[Any]


class AdditionalImage(BaseModel):
    canonical_images: Optional[CanonicalImages]
    image_signature: Optional[str]


class AggregatedPinData(BaseModel):
    aggregated_stats: Optional[AggregatedStats]
    comment_count: Optional[int]
    did_it_data: Optional[DidItData]
    id: Optional[str]
    is_shop_the_look: Optional[bool]


class Board(BaseModel):
    access: Optional[List]
    category: Optional[Any]
    collaborated_by_me: Optional[bool]
    description: Optional[str]
    followed_by_me: Optional[bool]
    id: Optional[str]
    image_cover_url: Optional[AnyUrl]
    image_thumbnail_url: Optional[AnyUrl]
    is_collaborative: Optional[bool]
    layout: Optional[str]
    map_id: Optional[str]
    name: Optional[str]
    owner: Optional[CloseupAttribution]
    pin_thumbnail_urls: Optional[List[AnyUrl]]
    privacy: Optional[str]
    type: Optional[str]
    url: Optional[str]


class ClientContext(BaseModel):
    analysis_ua: Optional[AnalysisUa]
    app_type_detailed: Optional[int]
    app_version: Optional[str]
    batch_exp: Optional[bool]
    browser_locale: Optional[str]
    browser_name: Optional[str]
    browser_type: Optional[int]
    browser_version: Optional[str]
    country: Optional[str]
    country_from_hostname: Optional[str]
    country_from_ip: Optional[str]
    csp_nonce: Optional[str]
    current_url: Optional[str]
    debug: Optional[bool]
    deep_link: Optional[str]
    enabled_advertiser_countries: Optional[List[str]]
    facebook_token: Optional[Any]
    full_path: Optional[str]
    http_referrer: Optional[str]
    impersonator_user_id: Optional[Any]
    invite_code: Optional[str]
    invite_sender_id: Optional[str]
    is_authenticated: Optional[bool]
    is_bot: Optional[str]
    is_full_page: Optional[bool]
    is_internal_ip: Optional[bool]
    is_managed_advertiser: Optional[bool]
    is_mobile_agent: Optional[bool]
    is_shop_the_pin_campaign_whitelisted: Optional[bool]
    is_sterling_on_steroids: Optional[bool]
    is_tablet_agent: Optional[bool]
    language: Optional[str]
    locale: Optional[str]
    origin: Optional[AnyUrl]
    path: Optional[str]
    placed_experiences: Optional[Any]
    referrer: Optional[Any]
    region_from_ip: Optional[str]
    request_host: Optional[str]
    request_identifier: Optional[str]
    seo_debug: Optional[bool]
    social_bot: Optional[str]
    stage: Optional[str]
    sterling_on_steroids_ldap: Optional[Any]
    sterling_on_steroids_user_type: Optional[Any]
    unauth_id: Optional[str]
    user: Optional[User]
    user_agent: Optional[str]
    user_agent_can_use_native_app: Optional[bool]
    user_agent_platform: Optional[str]
    user_agent_platform_version: Optional[Any]
    utm_campaign: Optional[Any]
    visible_url: Optional[str]


class Product(BaseModel):
    additional_images: Optional[List[AdditionalImage]]
    additional_images_per_spec: Optional[AdditionalImagesPerSpec]
    has_multi_images: Optional[bool]
    id: Optional[str]
    item_id: Optional[str]
    item_set_id: Optional[str]
    label_info: Optional[VerifiedIdentity]
    name: Optional[str]
    offer_summary: Optional[OfferSummary]
    offers: Optional[List]
    purchase_url: Optional[Any]
    shipping_info: Optional[VerifiedIdentity]
    type: Optional[str]
    variant_set: Optional[Any]
    videos: Optional[List]


class RichMetadata(BaseModel):
    aggregate_rating: Optional[AggregateRating]
    amp_url: Optional[str]
    amp_valid: Optional[bool]
    apple_touch_icon_images: Optional[Any]
    apple_touch_icon_link: Optional[Any]
    canonical_url: Optional[Any]
    description: Optional[str]
    favicon_images: Optional[FaviconImages]
    favicon_link: Optional[AnyUrl]
    has_price_drop: Optional[bool]
    id: Optional[str]
    link_status: Optional[int]
    locale: Optional[str]
    products: Optional[List[Product]]
    site_name: Optional[str]
    title: Optional[str]
    tracker: Optional[Any]
    type: Optional[str]
    url: Optional[AnyUrl]


class Data(BaseModel):
    access: Optional[List]
    images: Optional[Dict[str, Image]]
    videos: Optional[Any]

    aggregated_pin_data: Optional[AggregatedPinData]
    alt_text: Optional[Any]
    attribution: Optional[Any]
    auto_alt_text: Optional[Any]
    board: Optional[Board]
    buyable_product_availability: Optional[Any]
    can_delete_did_it_and_comments: Optional[bool]
    carousel_data: Optional[Any]
    category: Optional[str]
    closeup_attribution: Optional[CloseupAttribution]
    closeup_description: Optional[str]
    closeup_unified_description: Optional[str]
    closeup_user_note: Optional[str]
    comment_count: Optional[int]
    comments_disabled: Optional[bool]
    content_sensitivity: Optional[VerifiedIdentity]
    created_at: Optional[str]
    creator_class: Optional[Any]
    creator_class_instance: Optional[Any]
    description: Optional[str]
    description_html: Optional[str]
    did_it_disabled: Optional[bool]
    domain: Optional[str]
    dominant_color: Optional[str]
    embed: Optional[Any]
    grid_title: Optional[str]
    hashtags: Optional[List]
    id: Optional[str]
    image_medium_url: Optional[AnyUrl]
    image_signature: Optional[str]
    is_eligible_for_aggregated_comments: Optional[bool]
    is_eligible_for_brand_catalog: Optional[bool]
    is_eligible_for_pdp: Optional[bool]
    is_hidden: Optional[bool]
    is_native: Optional[bool]
    is_oos_product: Optional[bool]
    is_playable: Optional[bool]
    is_promotable: Optional[bool]
    is_promoted: Optional[bool]
    is_quick_promotable: Optional[bool]
    is_quick_promotable_by_pinner: Optional[bool]
    is_repin: Optional[bool]
    is_stale_product: Optional[bool]
    is_video: Optional[bool]
    is_whitelisted_for_tried_it: Optional[bool]
    link: Optional[AnyUrl]
    link_domain: Optional[LinkDomain]
    method: Optional[str]
    mobile_link: Optional[Any]
    music_attributions: Optional[List]
    native_creator: Optional[CloseupAttribution]
    origin_pinner: Optional[Any]
    pinned_to_board: Optional[Any]
    pinner: Optional[CloseupAttribution]
    price_currency: Optional[str]
    price_value: Optional[int]
    privacy: Optional[str]
    product_pin_data: Optional[Any]
    promoted_is_removable: Optional[bool]
    promoter: Optional[Any]
    reaction_counts: Optional[VerifiedIdentity]
    repin_count: Optional[int]
    rich_metadata: Optional[RichMetadata]
    section: Optional[Any]
    seo_url: Optional[str]
    share_count: Optional[int]
    shopping_flags: Optional[List[int]]
    shopping_rec_disabled: Optional[bool]
    should_mute: Optional[Any]
    should_open_in_stream: Optional[bool]
    should_redirect_id_only_url_to_text_url: Optional[bool]
    sponsorship: Optional[Any]
    story_pin_data: Optional[Any]
    story_pin_data_id: Optional[Any]
    third_party_pin_owner: Optional[Any]
    title: Optional[str]
    tracked_link: Optional[AnyUrl]
    tracking_params: Optional[str]
    type: Optional[str]
    via_pinner: Optional[Any]


class ResourceResponse(BaseModel):
    message: Optional[str]
    status: Optional[str]
    code: Optional[int]
    data: Optional[Data]
    endpoint_name: Optional[str]
    http_status: Optional[int]

    x_pinterest_sli_endpoint_name: Optional[str]


class PinterestResponseModel(BaseModel):
    resource_response: Optional[ResourceResponse]
    client_context: Optional[ClientContext]
    request_identifier: Optional[str]
    resource: Optional[Resource]
