########## SENSITIVE SECTION WARNING ###########
################################################
# Any edits of any of the exported names       #
# may result in a breaking change.             #
# Ensure no names are removed without warning. #
################################################


from __future__ import annotations

### DEP-WARN: Check this *every* discord.py update
from discord.ext.commands import (
    ArgumentParsingError,
    AutoShardedBot,
    BadArgument,
    BadBoolArgument,
    BadColourArgument,
    BadInviteArgument,
    BadUnionArgument,
    Bot,
    BotMissingAnyRole,
    BotMissingRole,
    BucketType,
    CategoryChannelConverter,
    ChannelNotFound,
    ChannelNotReadable,
    CheckAnyFailure,
    CheckFailure,
    CogMeta,
    ColorConverter,
    ColourConverter,
    CommandError,
    CommandInvokeError,
    CommandNotFound,
    CommandOnCooldown,
    CommandRegistrationError,
    ConversionError,
    Converter,
    Cooldown,
    CooldownMapping,
    DefaultHelpCommand,
    DisabledCommand,
    EmojiConverter,
    EmojiNotFound,
    ExpectedClosingQuoteError,
    ExtensionAlreadyLoaded,
    ExtensionError,
    ExtensionFailed,
    ExtensionNotFound,
    ExtensionNotLoaded,
    GameConverter,
    Greedy,
    GuildConverter,
    GuildNotFound,
    HelpCommand,
    IDConverter,
    InvalidEndOfQuotedStringError,
    InviteConverter,
    MaxConcurrency,
    MaxConcurrencyReached,
    MemberConverter,
    MemberNotFound,
    MessageConverter,
    MessageNotFound,
    MinimalHelpCommand,
    MissingAnyRole,
    MissingPermissions,
    MissingRequiredArgument,
    MissingRole,
    NoEntryPointError,
    NoPrivateMessage,
    NotOwner,
    NSFWChannelRequired,
    Paginator,
    PartialEmojiConversionFailure,
    PartialEmojiConverter,
    PartialMessageConverter,
    PrivateMessageOnly,
    RoleConverter,
    RoleNotFound,
    StageChannelConverter,
    StoreChannelConverter,
    TextChannelConverter,
    TooManyArguments,
    UnexpectedQuoteError,
    UserConverter,
    UserInputError,
    UserNotFound,
    VoiceChannelConverter,
    bot_has_guild_permissions,
    check_any,
    clean_content,
    max_concurrency,
)

from ._dpy_reimplements import (
    after_invoke,
    before_invoke,
    bot_has_any_role,
    bot_has_role,
    check,
    cooldown,
    dm_only,
    guild_only,
    has_any_role,
    has_role,
    is_nsfw,
    when_mentioned,
    when_mentioned_or,
)
from .commands import (
    RESERVED_COMMAND_NAMES,
    Cog,
    CogCommandMixin,
    CogGroupMixin,
    CogMixin,
    Command,
    Group,
    GroupMixin,
    RedUnhandledAPI,
    command,
    group,
)
from .context import Context, DMContext, GuildContext
from .converter import (
    CogConverter,
    CommandConverter,
    DictConverter,
    Literal,
    NoParseOptional,
    RelativedeltaConverter,
    TimedeltaConverter,
    UserInputOptional,
    get_dict_converter,
    get_timedelta_converter,
    parse_relativedelta,
    parse_timedelta,
)
from .errors import (
    ArgParserFailure,
    BotMissingPermissions,
    ConversionFailure,
    UserFeedbackCheckFailure,
)
from .help import HelpSettings, RedHelpFormatter, red_help
from .requires import (
    DM_PERMS,
    CheckPredicate,
    GlobalPermissionModel,
    GuildPermissionModel,
    PermissionModel,
    PermState,
    PrivilegeLevel,
    Requires,
    admin,
    admin_or_permissions,
    bot_has_permissions,
    bot_in_a_guild,
    guildowner,
    guildowner_or_permissions,
    has_guild_permissions,
    has_permissions,
    is_owner,
    mod,
    mod_or_permissions,
    permissions_check,
)
