# generated by datamodel-codegen:
#   timestamp: 2023-01-08T12:31:34+00:00


from __future__ import annotations

from typing import Any

from melanie import BaseModel


class CommentInformTreatment(BaseModel):
    should_have_inform_treatment: bool | None
    text: str | None
    url: Any | None
    action_type: Any | None


class ProfilePicture(BaseModel):
    uri: str | None


class EffectActionSheet(BaseModel):
    primary_actions: list[str] | None
    secondary_actions: list[str] | None


class EffectPreview(BaseModel):
    thumbnail_image: ProfilePicture | None


class CroppedImageVersion(BaseModel):
    width: int | None
    height: int | None
    url: str | None
    scans_profile: str | None


class SharingFrictionInfo(BaseModel):
    should_have_sharing_friction: bool | None
    bloks_app_url: Any | None
    sharing_friction_payload: Any | None


class IgMention(BaseModel):
    account_id: str | None
    username: str | None
    full_name: str | None
    profile_pic_url: str | None


class Hashtag(BaseModel):
    name: str | None
    id: str | None


class MusicAssetInfo(BaseModel):
    audio_cluster_id: str | None
    id: str | None
    title: str | None
    sanitized_title: Any | None
    subtitle: str | None
    display_artist: str | None
    artist_id: Any | None
    cover_artwork_uri: str | None
    cover_artwork_thumbnail_uri: str | None
    progressive_download_url: str | None
    reactive_audio_download_url: Any | None
    fast_start_progressive_download_url: Any | None
    web_30s_preview_download_url: Any | None
    highlight_start_times_in_ms: list | None
    is_explicit: bool | None
    dash_manifest: Any | None
    has_lyrics: bool | None
    audio_asset_id: str | None
    duration_in_ms: int | None
    dark_message: Any | None
    allows_saving: bool | None
    territory_validity_periods: Any | None
    ig_username: Any | None
    ig_artist: Any | None
    placeholder_profile_pic_url: str | None
    should_mute_audio: bool | None
    should_mute_audio_reason: str | None
    should_mute_audio_reason_type: str | None
    is_bookmarked: bool | None
    overlap_duration_in_ms: int | None
    audio_asset_start_time_in_ms: int | None
    allow_media_creation_with_music: bool | None
    is_trending_in_clips: bool | None
    formatted_clips_media_count: Any | None
    streaming_services: Any | None
    display_labels: Any | None
    should_allow_music_editing: bool | None


class ItemUser(BaseModel):
    pk: str | None
    is_private: bool | None


class VideoVersion(BaseModel):
    type: int | None
    width: int | None
    height: int | None
    url: str | None
    id: str | None


class ReelsMediaUser(BaseModel):
    pk: str | None
    username: str | None
    is_verified: bool | None
    profile_pic_id: str | None
    profile_pic_url: str | None
    pk_id: str | None
    full_name: str | None
    is_private: bool | None


class CoverMedia(BaseModel):
    cropped_image_version: CroppedImageVersion | None
    crop_rect: Any | None
    media_id: Any | None
    full_image_version: Any | None
    upload_id: Any | None


class AttributionUser(BaseModel):
    instagram_user_id: str | None
    username: str | None
    profile_picture: ProfilePicture | None


class EffectConfig(BaseModel):
    name: str | None
    id: str | None
    failure_reason: str | None
    failure_code: str | None
    is_creative_tool: bool | None
    gatekeeper: Any | None
    attribution_user_id: str | None
    attribution_user: AttributionUser | None
    gatelogic: Any | None
    save_status: str | None
    effect_actions: list[str] | None
    is_spot_recognition_effect: bool | None
    is_spot_effect: bool | None
    thumbnail_image: ProfilePicture | None
    effect_action_sheet: EffectActionSheet | None
    device_position: Any | None
    fan_club: Any | None


class ImageVersions2(BaseModel):
    candidates: list[CroppedImageVersion] | None


class StickerData(BaseModel):
    ig_mention: IgMention | None


class Story(BaseModel):
    x: float | None
    y: float | None
    z: int | None
    width: float | None
    height: float | None
    rotation: float | None
    is_pinned: int | None
    is_hidden: int | None
    is_sticker: int | None
    is_fb_sticker: int | None
    media_id: str | None
    product_type: str | None
    media_code: str | None
    hashtag: Hashtag | None
    attribution: str | None
    display_type: str | None
    music_asset_info: MusicAssetInfo | None


class CreativeConfig(BaseModel):
    camera_facing: str | None
    effect_ids: list[int] | None
    face_effect_id: str | None
    persisted_effect_metadata_json: str | None
    capture_type: str | None
    should_render_try_it_on: bool | None
    effect_id: str | None
    effect_configs: list[EffectConfig] | None
    name: str | None
    effect_name: str | None
    effect_actions: list[str] | None
    effect_action_sheet: EffectActionSheet | None
    device_position: Any | None
    save_status: str | None
    is_spot_recognition_effect: bool | None
    is_spot_effect: bool | None
    effect_preview: EffectPreview | None
    attribution_user: AttributionUser | None
    attribution_username: str | None
    attribution_id: str | None


class BloksSticker(BaseModel):
    id: str | None
    app_id: str | None
    sticker_data: StickerData | None
    bloks_sticker_type: str | None


class StoryBloksSticker(BaseModel):
    bloks_sticker: BloksSticker | None
    x: float | None
    y: float | None
    z: int | None
    width: float | None
    height: float | None
    rotation: float | None


class Item(BaseModel):
    taken_at: int | None
    pk: str | None
    id: str | None
    device_timestamp: int | None
    media_type: int | None
    code: str | None
    client_cache_key: str | None
    filter_type: int | None
    accessibility_caption: str | None
    is_unified_video: bool | None
    should_request_ads: bool | None
    original_media_has_visual_reply_media: bool | None
    caption_is_edited: bool | None
    like_and_view_counts_disabled: bool | None
    commerciality_status: str | None
    is_paid_partnership: bool | None
    is_visual_reply_commenter_notice_enabled: bool | None
    clips_tab_pinned_user_ids: list | None
    has_delayed_metadata: bool | None
    caption_position: float | None
    is_reel_media: bool | None
    photo_of_you: bool | None
    is_organic_product_tagging_eligible: bool | None
    can_see_insights_as_brand: bool | None
    user: ItemUser | None
    image_versions2: ImageVersions2 | None
    original_width: int | None
    original_height: int | None
    caption: Any | None
    comment_inform_treatment: CommentInformTreatment | None
    sharing_friction_info: SharingFrictionInfo | None
    can_viewer_save: bool | None
    is_in_profile_grid: bool | None
    profile_grid_control_enabled: bool | None
    organic_tracking_token: str | None
    imported_taken_at: int | None
    has_shared_to_fb: int | None
    product_type: str | None
    deleted_reason: int | None
    integrity_review_decision: str | None
    commerce_integrity_review_decision: Any | None
    music_metadata: Any | None
    is_artist_pick: bool | None
    can_reshare: bool | None
    can_reply: bool | None
    can_send_prompt: bool | None
    is_first_take: bool | None
    is_rollcall_v2: bool | None
    created_from_add_yours_browsing: bool | None
    story_bloks_stickers: list[StoryBloksSticker] | None
    story_static_models: list | None
    supports_reel_reactions: bool | None
    can_send_custom_emojis: bool | None
    show_one_tap_fb_share_tooltip: bool | None
    video_versions: list[VideoVersion] | None
    has_audio: bool | None
    video_duration: float | None
    story_music_stickers: list[Story] | None
    creative_config: CreativeConfig | None
    story_feed_media: list[Story] | None
    story_hashtags: list[Story] | None
    is_dash_eligible: int | None
    video_dash_manifest: str | None
    video_codec: str | None
    number_of_qualities: int | None
    has_translation: bool | None


class ReelsMedia(BaseModel):
    id: str | None
    latest_reel_media: int | None
    seen: Any | None
    can_reply: bool | None
    can_gif_quick_reply: bool | None
    can_reshare: bool | None
    can_react_with_avatar: bool | None
    reel_type: str | None
    ad_expiry_timestamp_in_millis: Any | None
    is_cta_sticker_available: Any | None
    cover_media: CoverMedia | None
    user: ReelsMediaUser | None
    items: list[Item] | None
    title: str | None
    created_at: int | None
    is_pinned_highlight: bool | None
    prefetch_count: int | None
    media_count: int | None
    media_ids: list[str] | None
    is_cacheable: bool | None
    is_converted_to_clips: bool | None
    disabled_reply_types: list[str] | None


class InstagramHighlightRaw(BaseModel):
    reels_media: list[ReelsMedia] | None
    status: str | None


class InstagramHighlightMediaItem(BaseModel):
    taken_at: float | None
    is_video: bool
    url: str


class InstagramHighlightResponse(BaseModel):
    id: str
    created_at: float | None
    latest_reel_media: float | None
    media_count: int | None
    items: list[InstagramHighlightMediaItem] = []
