# generated by datamodel-codegen:
#   timestamp: 2022-09-08T13:43:24+00:00


from __future__ import annotations

from typing import Any

from melanie import BaseModel, Field

from .instagram_post2 import InstagramUserResponse  # noqa


class FriendshipStatus(BaseModel):
    following: bool | None
    is_private: bool | None
    incoming_request: bool | None
    outgoing_request: bool | None
    is_bestie: bool | None
    is_restricted: bool | None
    is_feed_favorite: bool | None


class User(BaseModel):
    pk: int | None
    username: str | None
    full_name: str | None
    is_private: bool | None
    profile_pic_url: str | None
    profile_pic_id: str | None
    friendship_status: FriendshipStatus | None
    is_verified: bool | None


class Candidate(BaseModel):
    width: int | None
    height: int | None
    url: str | None


class ImageVersions2(BaseModel):
    candidates: list[Candidate] | None


class CommentInformTreatment(BaseModel):
    should_have_inform_treatment: bool | None
    text: str | None
    url: Any | None
    action_type: Any | None


class SharingFrictionInfo(BaseModel):
    should_have_sharing_friction: bool | None
    bloks_app_url: Any | None
    sharing_friction_payload: Any | None


class User1(BaseModel):
    pk: int | None
    is_private: bool | None


class StoryFeedMedia(BaseModel):
    x: float | None
    y: float | None
    z: int | None
    width: float | None
    height: float | None
    rotation: float | None
    is_pinned: int | None
    is_hidden: int | None
    is_sticker: int | None
    is_fb_sticker: int | None
    media_id: str | None
    product_type: str | None
    media_code: str | None
    clips_creation_entry_point: str | None


class VideoVersion(BaseModel):
    type: int | None
    width: int | None
    height: int | None
    url: str | None
    id: str | None


class IgMention(BaseModel):
    account_id: str | None
    username: str | None
    full_name: str | None
    profile_pic_url: str | None


class StickerData(BaseModel):
    ig_mention: IgMention | None


class BloksSticker(BaseModel):
    id: str | None
    app_id: str | None
    sticker_data: StickerData | None
    bloks_sticker_type: str | None


class StoryBloksSticker(BaseModel):
    bloks_sticker: BloksSticker | None
    x: float | None
    y: float | None
    z: int | None
    width: float | None
    height: float | None
    rotation: float | None


class Item(BaseModel):
    accessibility_caption: str | None
    can_reply: bool | None
    can_reshare: bool | None
    can_see_insights_as_brand: bool | None
    can_send_custom_emojis: bool | None
    can_send_prompt: bool | None
    can_viewer_save: bool | None
    caption_is_edited: bool | None
    caption_position: float | None
    caption: Any | None
    client_cache_key: str | None
    code: str | None
    comment_inform_treatment: CommentInformTreatment | None
    commerce_integrity_review_decision: Any | None
    commerciality_status: str | None
    deleted_reason: int | None
    device_timestamp: int | None
    expiring_at: int | None
    filter_type: int | None
    has_audio: bool | None
    has_delayed_metadata: bool | None
    has_shared_to_fb: int | None
    id: str | None
    image_versions2: ImageVersions2 | None
    integrity_review_decision: str | None
    is_artist_pick: bool | None
    is_dash_eligible: int | None
    is_in_profile_grid: bool | None
    is_organic_product_tagging_eligible: bool | None
    is_paid_partnership: bool | None
    is_reel_media: bool | None
    is_unified_video: bool | None
    is_visual_reply_commenter_notice_enabled: bool | None
    like_and_view_counts_disabled: bool | None
    media_type: int | None
    music_metadata: Any | None
    number_of_qualities: int | None
    organic_tracking_token: str | None
    original_height: int | None
    original_media_has_visual_reply_media: bool | None
    original_width: int | None
    photo_of_you: bool | None
    pk: str | None
    product_type: str | None
    profile_grid_control_enabled: bool | None
    sharing_friction_info: SharingFrictionInfo | None
    should_request_ads: bool | None
    show_one_tap_fb_share_tooltip: bool | None
    story_bloks_stickers: list[StoryBloksSticker] | None
    story_feed_media: list[StoryFeedMedia] | None
    story_static_models: list | None
    supports_reel_reactions: bool | None
    taken_at: int | None
    user: User1 | None
    video_codec: str | None
    video_dash_manifest: str | None
    video_duration: float | None
    video_versions: list[VideoVersion] | None


class Field1574083(BaseModel):
    id: int | None
    latest_reel_media: int | None
    expiring_at: int | None
    seen: int | None
    can_reply: bool | None
    can_gif_quick_reply: bool | None
    can_reshare: bool | None
    can_react_with_avatar: bool | None
    reel_type: str | None
    ad_expiry_timestamp_in_millis: Any | None
    is_cta_sticker_available: Any | None
    user: User | None
    items: list[Item] | None
    prefetch_count: int | None
    media_count: int | None
    media_ids: list[str] | None


class Reels(BaseModel):
    field_1574083: Field1574083 | None = Field(alias="1574083")


class FriendshipStatus1(FriendshipStatus):
    pass


class User2(BaseModel):
    pk: int | None
    username: str | None
    full_name: str | None
    is_private: bool | None
    profile_pic_url: str | None
    profile_pic_id: str | None
    friendship_status: FriendshipStatus1 | None
    is_verified: bool | None


class Candidate1(Candidate):
    pass


class ImageVersions21(BaseModel):
    candidates: list[Candidate1] | None


class CommentInformTreatment1(CommentInformTreatment):
    pass


class SharingFrictionInfo1(SharingFrictionInfo):
    pass


class User3(User1):
    pass


class StoryFeedMedia1(StoryFeedMedia):
    pass


class VideoVersion1(VideoVersion):
    pass


class IgMention1(IgMention):
    pass


class StickerData1(BaseModel):
    ig_mention: IgMention1 | None


class BloksSticker1(BaseModel):
    id: str | None
    app_id: str | None
    sticker_data: StickerData1 | None
    bloks_sticker_type: str | None


class StoryBloksSticker1(BaseModel):
    bloks_sticker: BloksSticker1 | None
    x: float | None
    y: float | None
    z: int | None
    width: float | None
    height: float | None
    rotation: float | None


class Item1(BaseModel):
    taken_at: int | None
    pk: str | None
    id: str | None
    device_timestamp: int | None
    media_type: int | None
    code: str | None
    client_cache_key: str | None
    filter_type: int | None
    accessibility_caption: str | None
    is_unified_video: bool | None
    should_request_ads: bool | None
    caption_is_edited: bool | None
    like_and_view_counts_disabled: bool | None
    commerciality_status: str | None
    is_paid_partnership: bool | None
    is_visual_reply_commenter_notice_enabled: bool | None
    original_media_has_visual_reply_media: bool | None
    has_delayed_metadata: bool | None
    image_versions2: ImageVersions21 | None
    original_width: int | None
    original_height: int | None
    caption_position: float | None
    is_reel_media: bool | None
    photo_of_you: bool | None
    is_organic_product_tagging_eligible: bool | None
    can_see_insights_as_brand: bool | None
    caption: Any | None
    comment_inform_treatment: CommentInformTreatment1 | None
    sharing_friction_info: SharingFrictionInfo1 | None
    can_viewer_save: bool | None
    is_in_profile_grid: bool | None
    profile_grid_control_enabled: bool | None
    organic_tracking_token: str | None
    expiring_at: int | None
    has_shared_to_fb: int | None
    product_type: str | None
    deleted_reason: int | None
    integrity_review_decision: str | None
    commerce_integrity_review_decision: Any | None
    music_metadata: Any | None
    is_artist_pick: bool | None
    user: User3 | None
    can_reshare: bool | None
    can_reply: bool | None
    can_send_prompt: bool | None
    story_feed_media: list[StoryFeedMedia1] | None
    story_static_models: list | None
    supports_reel_reactions: bool | None
    can_send_custom_emojis: bool | None
    show_one_tap_fb_share_tooltip: bool | None
    is_dash_eligible: int | None
    video_dash_manifest: str | None
    video_codec: str | None
    number_of_qualities: int | None
    video_versions: list[VideoVersion1] | None
    has_audio: bool | None
    video_duration: float | None
    story_bloks_stickers: list[StoryBloksSticker1] | None


class ReelsMedia(BaseModel):
    id: int | None
    latest_reel_media: int | None
    expiring_at: int | None
    seen: int | None
    can_reply: bool | None
    can_gif_quick_reply: bool | None
    can_reshare: bool | None
    can_react_with_avatar: bool | None
    reel_type: str | None
    ad_expiry_timestamp_in_millis: Any | None
    is_cta_sticker_available: Any | None
    user: User2 | None
    items: list[Item1] | None
    prefetch_count: int | None
    media_count: int | None
    media_ids: list[str] | None


class InstaStoryModel(BaseModel):
    reels: Reels | None
    reels_media: list[ReelsMedia] | None
    status: str | None
    created_at: int | None


class StoryItem(BaseModel):
    id: str | None
    is_video: bool | None
    filename: str | None
    url: str | None
    taken_at: int | None

    video_bytes: bytes | None = Field(None, exclude=True)


class InstagramStoryResponse(BaseModel):
    author: InstagramUserResponse | None = None
    items: list[StoryItem] | None = []
    item_count: int | None = None
    created_at: int | None = None
