# generated by datamodel-codegen:
#   timestamp: 2023-07-18T21:49:33+00:00

from __future__ import annotations

from typing import Annotated

from melanie import AnyUrl, BaseModel, Field


class Caption(BaseModel):
    text: str | None


class ConsumptionInfo(BaseModel):
    is_trending_in_clips: bool | None


class IgArtist(BaseModel):
    profile_pic_url: AnyUrl | None

    username: str | None


class VideoVersion(BaseModel):
    height: int | None
    url: AnyUrl | None
    width: int | None
    type: int | None


class FriendshipStatus(BaseModel):
    following: bool | None

    is_feed_favorite: bool | None

    outgoing_request: bool | None

    is_restricted: bool | None
    is_bestie: bool | None


class PageInfo(BaseModel):
    end_cursor: str | None
    has_next_page: bool | None
    has_previous_page: bool | None


class OriginalSoundInfo(BaseModel):
    audio_asset_id: str | None
    ig_artist: IgArtist | None
    original_audio_title: str | None
    is_explicit: bool | None
    consumption_info: ConsumptionInfo | None


class ImageVersions2(BaseModel):
    candidates: list[VideoVersion] | None


class User(BaseModel):
    pk: str | None
    username: str | None
    profile_pic_url: AnyUrl | None
    friendship_status: FriendshipStatus | None
    is_private: bool | None
    typename: Annotated[str | None, Field(alias="__typename")]
    is_unpublished: bool | None


class ClipsMetadata(BaseModel):
    original_sound_info: OriginalSoundInfo | None


class Media(BaseModel):
    pk: str | None
    code: str | None
    like_count: int | None
    user: User | None
    has_liked: bool | None
    product_type: str | None
    like_and_view_counts_disabled: bool | None
    media_type: int | None
    clips_metadata: ClipsMetadata | None
    id: str | None
    organic_tracking_token: str | None
    caption: Caption | None
    comment_count: int | None
    can_viewer_reshare: bool | None
    image_versions2: ImageVersions2 | None
    has_audio: bool | None
    is_dash_eligible: int | None
    number_of_qualities: int | None
    video_dash_manifest: str | None
    original_height: int | None
    original_width: int | None
    video_versions: list[VideoVersion] | None
    taken_at: int | None


class Node(BaseModel):
    media: Media | None
    typename: Annotated[str | None, Field(alias="__typename")]


class Edge(BaseModel):
    node: Node | None
    cursor: str | None


class XdtAPIV1ClipsHomeConnection(BaseModel):
    edges: list[Edge] | None
    page_info: PageInfo | None


class IgReelsIndexRaw(BaseModel):
    xdt_api__v1__clips__home__connection: XdtAPIV1ClipsHomeConnection | None
