# generated by datamodel-codegen:
#   timestamp: 2023-02-06T16:09:58+00:00


from __future__ import annotations

from typing import Any

from melanie import BaseModel


class CommentInformTreatment(BaseModel):
    should_have_inform_treatment: bool | None
    text: str | None
    url: Any | None
    action_type: Any | None


class Candidate(BaseModel):
    width: int | None
    height: int | None
    url: str | None


class SharingFrictionInfo(BaseModel):
    should_have_sharing_friction: bool | None
    bloks_app_url: Any | None
    sharing_friction_payload: Any | None


class Hashtag(BaseModel):
    name: str | None
    id: str | None


class FriendshipStatus(BaseModel):
    following: bool | None
    is_private: bool | None
    incoming_request: bool | None
    outgoing_request: bool | None
    is_bestie: bool | None
    is_restricted: bool | None
    is_feed_favorite: bool | None


class TerritoryValidityPeriods(BaseModel):
    pass


class ItemUser(BaseModel):
    pk: str | None
    is_private: bool | None


class VideoVersion(BaseModel):
    type: int | None
    width: int | None
    height: int | None
    url: str | None
    id: str | None


class ImageVersions2(BaseModel):
    candidates: list[Candidate] | None


class IgArtistClass(BaseModel):
    pk: str | None
    pk_id: str | None
    username: str | None
    full_name: str | None
    is_private: bool | None
    is_verified: bool | None
    profile_pic_id: str | None
    profile_pic_url: str | None
    friendship_status: FriendshipStatus | None


class MusicAssetInfo(BaseModel):
    audio_cluster_id: str | None
    id: str | None
    title: str | None
    sanitized_title: Any | None
    subtitle: str | None
    display_artist: str | None
    artist_id: Any | None
    cover_artwork_uri: str | None
    cover_artwork_thumbnail_uri: str | None
    progressive_download_url: str | None
    reactive_audio_download_url: Any | None
    fast_start_progressive_download_url: str | None
    web_30s_preview_download_url: Any | None
    highlight_start_times_in_ms: list[int] | None
    is_explicit: bool | None
    dash_manifest: Any | None
    has_lyrics: bool | None
    audio_asset_id: str | None
    duration_in_ms: int | None
    dark_message: Any | None
    allows_saving: bool | None
    territory_validity_periods: TerritoryValidityPeriods | None
    ig_username: str | None
    ig_artist: IgArtistClass | None
    placeholder_profile_pic_url: str | None
    should_mute_audio: bool | None
    should_mute_audio_reason: str | None
    should_mute_audio_reason_type: Any | None
    is_bookmarked: bool | None
    overlap_duration_in_ms: int | None
    audio_asset_start_time_in_ms: int | None
    allow_media_creation_with_music: bool | None
    is_trending_in_clips: bool | None
    formatted_clips_media_count: Any | None
    streaming_services: Any | None
    display_labels: Any | None
    should_allow_music_editing: bool | None


class Story(BaseModel):
    x: float | None
    y: float | None
    z: int | None
    width: float | None
    height: float | None
    rotation: float | None
    is_pinned: int | None
    is_hidden: int | None
    is_sticker: int | None
    is_fb_sticker: int | None
    hashtag: Hashtag | None
    attribution: str | None
    display_type: str | None
    music_asset_info: MusicAssetInfo | None


class Item(BaseModel):
    taken_at: int | None
    pk: str | None
    id: str | None
    device_timestamp: int | None
    media_type: int | None
    code: str | None
    client_cache_key: str | None
    filter_type: int | None
    is_unified_video: bool | None
    should_request_ads: bool | None
    original_media_has_visual_reply_media: bool | None
    caption_is_edited: bool | None
    like_and_view_counts_disabled: bool | None
    commerciality_status: str | None
    is_paid_partnership: bool | None
    is_visual_reply_commenter_notice_enabled: bool | None
    clips_tab_pinned_user_ids: list | None
    has_delayed_metadata: bool | None
    caption_position: float | None
    is_reel_media: bool | None
    photo_of_you: bool | None
    is_organic_product_tagging_eligible: bool | None
    can_see_insights_as_brand: bool | None
    image_versions2: ImageVersions2 | None
    original_width: int | None
    original_height: int | None
    caption: Any | None
    comment_inform_treatment: CommentInformTreatment | None
    sharing_friction_info: SharingFrictionInfo | None
    is_dash_eligible: int | None
    video_dash_manifest: str | None
    video_codec: str | None
    number_of_qualities: int | None
    video_versions: list[VideoVersion] | None
    has_audio: bool | None
    video_duration: float | None
    can_viewer_save: bool | None
    is_in_profile_grid: bool | None
    profile_grid_control_enabled: bool | None
    organic_tracking_token: str | None
    expiring_at: int | None
    imported_taken_at: int | None
    has_shared_to_fb: int | None
    product_type: str | None
    deleted_reason: int | None
    integrity_review_decision: str | None
    commerce_integrity_review_decision: Any | None
    music_metadata: Any | None
    is_artist_pick: bool | None
    user: ItemUser | None
    can_reshare: bool | None
    can_reply: bool | None
    can_send_prompt: bool | None
    is_first_take: bool | None
    is_rollcall_v2: bool | None
    can_play_spotify_audio: bool | None
    created_from_add_yours_browsing: bool | None
    story_static_models: list | None
    supports_reel_reactions: bool | None
    can_send_custom_emojis: bool | None
    show_one_tap_fb_share_tooltip: bool | None
    accessibility_caption: str | None
    story_music_stickers: list[Story] | None
    story_hashtags: list[Story] | None


class Reels(BaseModel):
    id: str | None
    latest_reel_media: int | None
    expiring_at: int | None
    seen: int | None
    can_reply: bool | None
    can_gif_quick_reply: bool | None
    can_reshare: bool | None
    can_react_with_avatar: bool | None
    reel_type: str | None
    ad_expiry_timestamp_in_millis: Any | None
    is_cta_sticker_available: Any | None
    user: IgArtistClass | None
    items: list[Item] | None
    prefetch_count: int | None
    media_count: int | None
    media_ids: list[str] | None
    is_cacheable: bool | None
    disabled_reply_types: list[str] | None


class InstagramStorylinkRaw(BaseModel):
    reels: dict[str, Reels] | None
    reels_media: list[Reels] | None
    status: str | None
