# generated by datamodel-codegen:
#   timestamp: 2023-08-09T09:27:21+00:00

from __future__ import annotations

from typing import Annotated

from melanie import BaseModel, Field


class AffiliatesHighlightedLabel(BaseModel):
    pass


class HighlightsInfo(BaseModel):
    can_highlight_tweets: bool | None
    highlighted_tweets: int | None


class URL(BaseModel):
    display_url: str | None
    expanded_url: str | None
    url: str | None
    indices: list[int] | None


class Birthdate(BaseModel):
    day: int | None
    month: int | None
    visibility: str | None
    year_visibility: str | None


class PurpleRef(BaseModel):
    type: str | None
    url: str | None
    url_type: Annotated[str | None, Field(alias="urlType")]


class FluffyRef(BaseModel):
    url: str | None
    url_type: str | None


class URLClass(BaseModel):
    urls: list[URL] | None


class LegacyExtendedProfile(BaseModel):
    birthdate: Birthdate | None


class UnavailableMessageEntity(BaseModel):
    from_index: Annotated[int | None, Field(alias="fromIndex")]
    to_index: Annotated[int | None, Field(alias="toIndex")]
    ref: PurpleRef | None


class DescriptionEntity(BaseModel):
    from_index: int | None
    to_index: int | None
    ref: FluffyRef | None


class Entities(BaseModel):
    description: URLClass | None
    url: URLClass | None


class UnavailableMessage(BaseModel):
    rtl: bool | None
    text: str | None
    entities: list[UnavailableMessageEntity] | None


class ReasonDescription(BaseModel):
    text: str | None
    entities: list[DescriptionEntity] | None


class Legacy(BaseModel):
    protected: bool | None
    can_dm: bool | None
    can_media_tag: bool | None
    created_at: str | None
    default_profile: bool | None
    default_profile_image: bool | None
    description: str | None
    entities: Entities | None
    fast_followers_count: int | None
    favourites_count: int | None
    followers_count: int | None
    friends_count: int | None
    has_custom_timelines: bool | None
    is_translator: bool | None
    listed_count: int | None
    location: str | None
    media_count: int | None
    name: str | None
    normal_followers_count: int | None
    pinned_tweet_ids_str: list[str] | None
    possibly_sensitive: bool | None
    profile_image_url_https: str | None
    profile_interstitial_type: str | None
    screen_name: str | None
    statuses_count: int | None
    translator_type: str | None
    verified: bool | None
    want_retweets: bool | None
    withheld_in_countries: list | None
    profile_banner_url: str | None
    url: str | None
    verified_type: str | None


class Reason(BaseModel):
    description: ReasonDescription | None
    verified_since_msec: str | None


class VerificationInfo(BaseModel):
    reason: Reason | None


class TweetDataResult(BaseModel):
    field__typename: Annotated[str | None, Field(alias="__typename")]
    id: str | None
    rest_id: str | None
    affiliates_highlighted_label: AffiliatesHighlightedLabel | None
    has_graduated_access: bool | None
    is_blue_verified: bool | None
    profile_image_shape: str | None
    legacy: Legacy | None
    smart_blocked_by: bool | None
    smart_blocking: bool | None
    legacy_extended_profile: LegacyExtendedProfile | None
    is_profile_translatable: bool | None
    has_hidden_subscriptions_on_profile: bool | None
    verification_info: VerificationInfo | None
    highlights_info: HighlightsInfo | None
    business_account: AffiliatesHighlightedLabel | None
    creator_subscriptions_count: int | None
    unavailable_message: UnavailableMessage | None
    reason: str | None


class User(BaseModel):
    result: TweetDataResult | None


class Data(BaseModel):
    user: User | None


class UserTweetsModel(BaseModel):
    data: Data | None
