# generated by datamodel-codegen:
#   timestamp: 2023-02-04T02:19:05+00:00


from __future__ import annotations

from melanie import BaseModel


class TwitterUserLookupResponse(BaseModel):
    id: str | None
    name: str | None
    screen_name: str | None
    location: str | None
    description: str | None
    url: str | None
    protected: bool | None
    followers_count: int | None
    friends_count: int | None
    listed_count: int | None
    created_at: str | None
    utc_offset: str | None
    time_zone: str | None
    geo_enabled: bool | None
    verified: bool | None
    statuses_count: int | None
    avatar_url: str | None
