# generated by datamodel-codegen:
#   timestamp: 2022-10-04T01:56:21+00:00


from __future__ import annotations

import pydantic


class Settings(pydantic.BaseSettings):
    api_base_url: str
    ocr_key: str
    sp_client_secret: str
    sp_client_id: str
    sp_redirect_url: str
    dask_host: str
    dask_scheduler_url: str
    db_url: str
    melanie_db_url: str
    path: str
    redis_url: str
    tenor_key: str


try:
    settings = Settings()
except Exception:
    settings = {}
