# generated by datamodel-codegen:
#   timestamp: 2022-12-30T00:57:38+00:00


from __future__ import annotations

from typing import Annotated

from melanie import AnyUrl, BaseModel, Field


class Avatar(BaseModel):
    image_url: AnyUrl | None
    initial: str | None
    accent_color: str | None


class MetaTag(BaseModel):
    name: str | None
    content: str | None
    property: str | None


class WindowVariables(BaseModel):
    profile: str | None


class Query(BaseModel):
    pass


class PageProps(BaseModel):
    csp_nonce: Annotated[str | None, Field(alias="cspNonce")]
    page_title: Annotated[str | None, Field(alias="pageTitle")]
    meta_tags: Annotated[list[MetaTag] | None, Field(alias="metaTags")]
    window_variables: Annotated[WindowVariables | None, Field(alias="windowVariables")]


class Props(BaseModel):
    page_props: Annotated[PageProps | None, Field(alias="pageProps")]
    n_ssg: Annotated[bool | None, Field(alias="__N_SSG")]


class CashappRaw(BaseModel):
    props: Props | None
    query: Query | None
    build_id: Annotated[str | None, Field(alias="buildId")]
    asset_prefix: Annotated[AnyUrl | None, Field(alias="assetPrefix")]
    is_fallback: Annotated[bool | None, Field(alias="isFallback")]
    gsp: bool | None
    script_loader: Annotated[list | None, Field(alias="scriptLoader")]
    display_name: str | None
    formatted_cashtag: str | None
    is_verified_account: bool | None
    rate_plan: str | None
    payment_button_type: str | None
    country_code: str | None
    avatar: Avatar | None


class CashAppProfile(BaseModel):
    display_name: str | None
    formatted_cashtag: str | None
    is_verified_account: bool | None
    rate_plan: str | None
    payment_button_type: str | None
    country_code: str | None
    avatar: Avatar | None


class CashappProfileResponse(BaseModel):
    profile: CashAppProfile | None
    qr_image_url: str | None
