# generated by datamodel-codegen:
#   timestamp: 2022-09-26T11:14:56+00:00


from __future__ import annotations

from typing import Any

from melanie import BaseModel


class BasicMeInfo(BaseModel):
    id: str | None
    username: str | None
    avatar: str | None
    avatar_decoration: Any | None
    discriminator: str | None
    public_flags: int | None
    flags: int | None
    banner: Any | None
    banner_color: str | None
    accent_color: int | None
    locale: str | None
    mfa_enabled: bool | None
    premium_type: int | None
    email: str | None
    verified: bool | None
