# generated by datamodel-codegen:
#   timestamp: 2022-10-24T01:44:07+00:00


from __future__ import annotations

from melanie.models.base import BaseModel


class Author(BaseModel):
    avatar_larger: str | None
    avatar_medium: str | None
    avatar_thumb: str | None
    comment_setting: int | None
    download_setting: int | None
    duet_setting: int | None
    ftc: bool | None
    id: str | None
    is_ad_virtual: bool | None
    nickname: str | None
    open_favorite: bool | None
    private_account: bool | None
    relation: int | None
    secret: bool | None
    signature: str | None
    stitch_setting: int | None
    tt_seller: bool | None
    unique_id: str | None
    verified: bool | None
    room_id: str | None


class AuthorStats(BaseModel):
    digg_count: int | None
    follower_count: int | None
    following_count: int | None
    heart: int | None
    video_count: int | None


class ChallengeStats(BaseModel):
    video_count: int | None
    view_count: int | None


class DuetInfo(BaseModel):
    duet_from_id: str | None


class StickerStats(BaseModel):
    use_count: int | None


class Music(BaseModel):
    author_name: str | None
    cover_large: str | None
    cover_medium: str | None
    cover_thumb: str | None
    duration: int | None
    id: str | None
    original: bool | None
    play_url: str | None
    title: str | None
    album: str | None


class TiktokStats(BaseModel):
    comment_count: int | None
    digg_count: int | None
    play_count: int | None
    share_count: int | None


class StickersOnItem(BaseModel):
    sticker_text: list[str] | None
    sticker_type: int | None


class VolumeInfo(BaseModel):
    loudness: float | None
    peak: float | None


class WarnInfo(BaseModel):
    key: str | None
    lang: str | None
    text: str | None
    type: int | None


class Challenge(BaseModel):
    id: str | None
    is_commerce: bool | None
    stats: ChallengeStats | None
    title: str | None
    cover_larger: str | None
    cover_medium: str | None
    cover_thumb: str | None
    desc: str | None
    profile_larger: str | None
    profile_medium: str | None
    profile_thumb: str | None


class EffectSticker(BaseModel):
    id: int | None
    name: str | None
    sticker_stats: StickerStats | None


class Video(BaseModel):
    bitrate: int | None
    codec_type: str | None
    cover: str | None
    definition: str | None
    download_addr: str | None
    duration: int | None
    dynamic_cover: str | None
    encoded_type: str | None
    format: str | None
    height: int | None
    id: str | None
    origin_cover: str | None
    play_addr: str | None
    ratio: str | None
    reflow_cover: str | None
    share_cover: list[str] | None
    video_quality: str | None
    volume_info: VolumeInfo | None
    width: int | None
    zoom_cover: dict[str, str] | None


class UserLikesTikTok(BaseModel):
    ad_authorization: bool | None
    share_url: str | None
    ad_label_version: int | None
    author: Author | None
    author_stats: AuthorStats | None
    challenges: list[Challenge] | None
    create_time: int | None
    desc: str | None
    digged: bool | None
    duet_display: int | None
    duet_enabled: bool | None
    duet_info: DuetInfo | None
    for_friend: bool | None
    id: str | None
    is_ad: bool | None
    item_comment_status: int | None
    item_mute: bool | None
    music: Music | None
    offical_item: bool | None
    original_item: bool | None
    private_item: bool | None
    secret: bool | None
    share_enabled: bool | None
    show_not_pass: bool | None
    stats: TiktokStats | None
    stickers_on_item: list[StickersOnItem] | None
    stitch_display: int | None
    stitch_enabled: bool | None
    video: Video | None
    vl1: bool | None
    effect_stickers: list[EffectSticker] | None
    mask_type: int | None
    warn_info: list[WarnInfo] | None


class RawUserLikesResponse(BaseModel):
    quantity: int = 0
    tiktoks: list[UserLikesTikTok] | None = []
