# generated by datamodel-codegen:
#   timestamp: 2022-12-27T06:02:04+00:00


from __future__ import annotations

from typing import Any

from melanie import BaseModel, Field


class PremiumSettings(BaseModel):
    show_early_adopter_badge: bool | None = Field(None, alias="showEarlyAdopterBadge")
    show_subscriber_badge: bool | None = Field(None, alias="showSubscriberBadge")
    show_premium_profile_page: bool | None = Field(None, alias="showPremiumProfilePage")
    show_premium_social_activity: bool | None = Field(None, alias="showPremiumSocialActivity")


class Role(BaseModel):
    id: str | None
    category_id: str | None = Field(None, alias="categoryId")
    name: str | None
    description: str | None
    icon: str | None


class State(BaseModel):
    type: str | None
    is_success: bool | None = Field(None, alias="isSuccess")
    is_shareable: bool | None = Field(None, alias="isShareable")


class Poster(BaseModel):
    user_id: int | None = Field(None, alias="userId")
    publisher: bool | None
    display_name: str | None = Field(None, alias="displayName")
    thumbnail: str | None
    cover_photo: str | None = Field(None, alias="coverPhoto")
    slogan: str | None
    language_locale: Any | None = Field(None, alias="languageLocale")
    donate_config: Any | None = Field(None, alias="donateConfig")
    roles: list[Role] | None
    game_sessions: list | None = Field(None, alias="gameSessions")
    valorant_player: Any | None = Field(None, alias="valorantPlayer")
    status: Any | None
    icon: Any | None
    state: Any | None
    guest: bool | None
    premium_type: str | None = Field(None, alias="premiumType")
    premium_settings: PremiumSettings | None = Field(None, alias="premiumSettings")
    followers: int | None
    following: int | None
    upvotes: int | None
    submissions: int | None
    is_following: bool | None = Field(None, alias="isFollowing")
    is_followed_by: bool | None = Field(None, alias="isFollowedBy")
    is_blocked: bool | None = Field(None, alias="isBlocked")
    created_at: int | None = Field(None, alias="createdAt")
    contexts: list | None
    user_name: str | None = Field(None, alias="userName")


class MedalDataRaw(BaseModel):
    content_id: str | None = Field(None, alias="contentId")
    content_type: int | None = Field(None, alias="contentType")
    category_id: str | None = Field(None, alias="categoryId")
    privacy: int | None
    has_title: bool | None = Field(None, alias="hasTitle")
    content_title: str | None = Field(None, alias="contentTitle")
    content_description: str | None = Field(None, alias="contentDescription")
    tags: list | None
    user_tags: list | None = Field(None, alias="userTags")
    recent_comments: list | None = Field(None, alias="recentComments")
    music: list | None
    layers: list | None
    has_templates: bool | None = Field(None, alias="hasTemplates")
    client: str | None
    state: State | None
    risk: int | None
    unseen_count: int | None = Field(None, alias="unseenCount")
    source_width: int | None = Field(None, alias="sourceWidth")
    source_height: int | None = Field(None, alias="sourceHeight")
    video_length_seconds: int | None = Field(None, alias="videoLengthSeconds")
    parent: int | None
    poster: Poster | None
    content_url720p: str | None = Field(None, alias="contentUrl720p")
    content_url480p: str | None = Field(None, alias="contentUrl480p")
    content_url360p: str | None = Field(None, alias="contentUrl360p")
    content_url240p: str | None = Field(None, alias="contentUrl240p")
    content_url144p: str | None = Field(None, alias="contentUrl144p")
    content_preview1080p: str | None = Field(None, alias="contentPreview1080p")
    content_preview720p: str | None = Field(None, alias="contentPreview720p")
    content_preview480p: str | None = Field(None, alias="contentPreview480p")
    content_preview360p: str | None = Field(None, alias="contentPreview360p")
    content_preview240p: str | None = Field(None, alias="contentPreview240p")
    content_preview144p: str | None = Field(None, alias="contentPreview144p")
    thumbnail720p: str | None
    thumbnail480p: str | None
    thumbnail360p: str | None
    thumbnail240p: str | None
    thumbnail144p: str | None
    content_url: str | None = Field(None, alias="contentUrl")
    content_url_hls: str | None = Field(None, alias="contentUrlHls")
    social_media_video: str | None = Field(None, alias="socialMediaVideo")
    unique_guest_views: int | None = Field(None, alias="uniqueGuestViews")
    pin_position: int | None = Field(None, alias="pinPosition")
    support_match_stats: bool | None = Field(None, alias="supportMatchStats")
    created: int | None
    published_at: int | None = Field(None, alias="publishedAt")
    urls_expire_at: int | None = Field(None, alias="urlsExpireAt")
    likes: int | None
    views: int | None
    comments: int | None
    processed: int | None
    share_count: int | None = Field(None, alias="shareCount")
    has_access: int | None = Field(None, alias="hasAccess")
    has_sound: int | None = Field(None, alias="hasSound")
    use_native_discord_embed: bool | None = Field(None, alias="useNativeDiscordEmbed")
    orientation: str | None
    pinned: bool | None
    user_saved: int | None = Field(None, alias="userSaved")
    user_liked: int | None = Field(None, alias="userLiked")
    user_viewed: int | None = Field(None, alias="userViewed")


class MedalDownloadResponse(BaseModel):
    content_id: str | None
    content_type: int | None
    category_id: str | None
    privacy: int | None
    has_title: bool | None
    content_title: str | None
    content_description: str | None
    tags: list | None
    user_tags: list | None
    recent_comments: list | None
    music: list | None
    layers: list | None
    has_templates: bool | None
    client: str | None
    state: State | None
    risk: int | None
    unseen_count: int | None
    source_width: int | None
    source_height: int | None
    video_length_seconds: int | None
    parent: int | None
    poster: Poster | None
    content_url720p: str | None
    content_url480p: str | None
    content_url360p: str | None
    content_url240p: str | None
    content_url144p: str | None
    content_preview1080p: str | None
    content_preview720p: str | None
    content_preview480p: str | None
    content_preview360p: str | None
    content_preview240p: str | None
    content_preview144p: str | None
    thumbnail720p: str | None
    thumbnail480p: str | None
    thumbnail360p: str | None
    thumbnail240p: str | None
    thumbnail144p: str | None
    content_url: str | None
    content_url_hls: str | None
    social_media_video: str | None
    unique_guest_views: int | None
    pin_position: int | None
    support_match_stats: bool | None
    created: int | None
    published_at: int | None
    urls_expire_at: int | None
    likes: int | None
    views: int | None
    comments: int | None
    processed: int | None
    share_count: int | None
    has_access: int | None
    has_sound: int | None
    use_native_discord_embed: bool | None
    orientation: str | None
    pinned: bool | None
    user_saved: int | None
    user_liked: int | None
    user_viewed: int | None
