# generated by datamodel-codegen:
#   timestamp: 2023-05-04T00:47:28+00:00

from __future__ import annotations

from melanie import AnyUrl, BaseModel, Field


class PuneHedgehog(BaseModel):
    vid: str | None


class SearchVideo(BaseModel):
    vid: str | None
    bot_vid: str | None = Field(None, alias="botVid")


class TiktokWeb(BaseModel):
    can_use_long_caption: int | None
    use_markup_text: int | None


class QualityFilterClass(BaseModel):
    pass


class AutoBitrateParams(BaseModel):
    param_a: int | None = Field(None, alias="paramA")
    param_b: float | None = Field(None, alias="paramB")
    param_c: float | None = Field(None, alias="paramC")
    param_d: int | None = Field(None, alias="paramD")
    min_bitrate: int | None = Field(None, alias="minBitrate")


class BitrateConfigElement(BaseModel):
    bitrate_lower: int | None = Field(None, alias="bitrateLower")
    bitrate_range: list[int] | None = Field(None, alias="bitrateRange")
    bitrate_upper: int | None = Field(None, alias="bitrateUpper")
    mode: str | None
    param_bf: float | None = Field(None, alias="paramBf")
    param_bp: float | None = Field(None, alias="paramBp")
    param_lower: float | None = Field(None, alias="paramLower")
    param_upper: float | None = Field(None, alias="paramUpper")
    param_upper_bl: float | None = Field(None, alias="paramUpperBl")
    param_vl1: float | None = Field(None, alias="paramVl1")
    param_vl2: int | None = Field(None, alias="paramVl2")
    param_vl_lower: float | None = Field(None, alias="paramVlLower")
    param_vl_upper: float | None = Field(None, alias="paramVlUpper")
    sliding_window_count_threshold: int | None = Field(None, alias="slidingWindowCountThreshold")
    sliding_window_extraction: str | None = Field(None, alias="slidingWindowExtraction")
    sliding_window_type: str | None = Field(None, alias="slidingWindowType")
    sliding_window_weight: str | None = Field(None, alias="slidingWindowWeight")
    sliding_window_weight_threshold: int | None = Field(None, alias="slidingWindowWeightThreshold")
    quality_filter: QualityFilterClass | None
    white_list: list | None
    auto_bitrate_params: AutoBitrateParams | None = Field(None, alias="autoBitrateParams")
    default_bitrate: int | None = Field(None, alias="defaultBitrate")


class Resource(BaseModel):
    prefix: str | None
    themes: list[str] | None
    esm: str | None
    nomodule: str | None
    version: str | None


class FeatureFlags(BaseModel):
    feature_tt4b_ads: bool | None
    business_account_open: bool | None
    support_multiline_desc: bool | None
    pc_video_playlist: bool | None


class Meridiem(BaseModel):
    am: str | None
    pm: str | None
    am_1: str | None = Field(None, alias="AM")
    pm_1: str | None = Field(None, alias="PM")


class Amazon(BaseModel):
    visible: bool | None
    normal: AnyUrl | None


class OriginalSubdivision(BaseModel):
    geo_name_id: int | None = Field(None, alias="GeoNameID")
    asci_name: str | None = Field(None, alias="ASCIName")
    name: str | None = Field(None, alias="Name")


class LiveAnchorEntrance(BaseModel):
    live_center: bool | None = Field(None, alias="liveCenter")
    creator_hub: bool | None = Field(None, alias="creatorHub")
    live_studio: bool | None = Field(None, alias="liveStudio")


class LiveSuggestConfig(BaseModel):
    is_blocked_area: bool | None = Field(None, alias="isBlockedArea")
    is_risk_area: bool | None = Field(None, alias="isRiskArea")


class Child(BaseModel):
    title: str | None
    href: AnyUrl | None
    key: str | None


class PlaybackNormalizePath(BaseModel):
    path: list[str] | None


class VideoOrderElement(BaseModel):
    property: str | None
    detail: list[int] | None
    order: str | None


class VideoPlayerConfig(BaseModel):
    fallback: bool | None


class XgplayerInitHost(BaseModel):
    group1: list[str] | None
    group2: list[str] | None


class PreloadList(BaseModel):
    url: str | None
    id: str | None


class Challenge(BaseModel):
    id: int | None
    title: str | None
    desc: str | None
    profile_larger: str | None = Field(None, alias="profileLarger")
    profile_medium: str | None = Field(None, alias="profileMedium")
    profile_thumb: str | None = Field(None, alias="profileThumb")
    cover_larger: str | None = Field(None, alias="coverLarger")
    cover_medium: str | None = Field(None, alias="coverMedium")
    cover_thumb: str | None = Field(None, alias="coverThumb")


class TextExtra(BaseModel):
    aweme_id: str | None = Field(None, alias="awemeId")
    start: int | None
    end: int | None
    hashtag_id: int | None = Field(None, alias="hashtagId")
    hashtag_name: str | None = Field(None, alias="hashtagName")
    type: int | None
    sub_type: int | None = Field(None, alias="subType")
    is_commerce: bool | None = Field(None, alias="isCommerce")


class ImageURL(BaseModel):
    url_list: list[AnyUrl] | None = Field(None, alias="urlList")


class Cover(BaseModel):
    image_url: ImageURL | None = Field(None, alias="imageURL")
    image_width: int | None = Field(None, alias="imageWidth")
    image_height: int | None = Field(None, alias="imageHeight")


class Music(BaseModel):
    id: str | None
    title: str | None
    play_url: AnyUrl | None = Field(None, alias="playUrl")
    cover_large: AnyUrl | None = Field(None, alias="coverLarge")
    cover_medium: AnyUrl | None = Field(None, alias="coverMedium")
    cover_thumb: AnyUrl | None = Field(None, alias="coverThumb")
    author_name: str | None = Field(None, alias="authorName")
    original: bool | None
    duration: int | None
    schedule_search_time: int | None = Field(None, alias="scheduleSearchTime")


class ItemModuleStats(BaseModel):
    digg_count: int | None = Field(None, alias="diggCount")
    share_count: int | None = Field(None, alias="shareCount")
    comment_count: int | None = Field(None, alias="commentCount")
    play_count: int | None = Field(None, alias="playCount")
    collect_count: int | None = Field(None, alias="collectCount")


class PlayAddr(BaseModel):
    uri: str | None = Field(None, alias="Uri")
    url_list: list[AnyUrl] | None = Field(None, alias="UrlList")
    data_size: int | None = Field(None, alias="DataSize")
    url_key: str | None = Field(None, alias="UrlKey")
    file_hash: str | None = Field(None, alias="FileHash")
    file_cs: str | None = Field(None, alias="FileCs")


class SubtitleInfo(BaseModel):
    language_id: int | None = Field(None, alias="LanguageID")
    language_code_name: str | None = Field(None, alias="LanguageCodeName")
    url: AnyUrl | None = Field(None, alias="Url")
    url_expire: int | None = Field(None, alias="UrlExpire")
    format: str | None = Field(None, alias="Format")
    version: int | None = Field(None, alias="Version")
    source: str | None = Field(None, alias="Source")
    size: int | None = Field(None, alias="Size")


class VolumeInfo(BaseModel):
    loudness: float | None = Field(None, alias="Loudness")
    peak: float | None = Field(None, alias="Peak")


class WarnInfo(BaseModel):
    text: str | None


class AbtestParameters(BaseModel):
    video_page_serp_compliance: PuneHedgehog | None


class Item(BaseModel):
    field_type: str | None = Field(None, alias="@type")
    field_id: AnyUrl | None = Field(None, alias="@id")
    name: str | None


class MetaParams(BaseModel):
    title: str | None
    keywords: str | None
    description: str | None
    canonical_href: AnyUrl | None = Field(None, alias="canonicalHref")
    robots_content: str | None = Field(None, alias="robotsContent")
    applicable_device: str | None = Field(None, alias="applicableDevice")


class SharingMetaState(BaseModel):
    value: dict[str, str] | None


class Saintajinrealmfka(BaseModel):
    id: str | None
    short_id: str | None = Field(None, alias="shortId")
    unique_id: str | None = Field(None, alias="uniqueId")
    nickname: str | None
    avatar_larger: AnyUrl | None = Field(None, alias="avatarLarger")
    avatar_medium: AnyUrl | None = Field(None, alias="avatarMedium")
    avatar_thumb: AnyUrl | None = Field(None, alias="avatarThumb")
    signature: str | None
    create_time: int | None = Field(None, alias="createTime")
    verified: bool | None

    ftc: bool | None
    relation: int | None
    open_favorite: bool | None = Field(None, alias="openFavorite")
    comment_setting: int | None = Field(None, alias="commentSetting")
    duet_setting: int | None = Field(None, alias="duetSetting")
    stitch_setting: int | None = Field(None, alias="stitchSetting")
    private_account: bool | None = Field(None, alias="privateAccount")
    secret: bool | None
    is_ad_virtual: bool | None = Field(None, alias="isADVirtual")
    room_id: str | None = Field(None, alias="roomId")
    unique_id_modify_time: int | None = Field(None, alias="uniqueIdModifyTime")
    tt_seller: bool | None = Field(None, alias="ttSeller")
    download_setting: int | None = Field(None, alias="downloadSetting")
    recommend_reason: str | None = Field(None, alias="recommendReason")
    now_invitation_card_url: str | None = Field(None, alias="nowInvitationCardUrl")
    nick_name_modify_time: int | None = Field(None, alias="nickNameModifyTime")
    is_embed_banned: bool | None = Field(None, alias="isEmbedBanned")
    can_exp_playlist: bool | None = Field(None, alias="canExpPlaylist")


class VideoPage(BaseModel):
    status_code: int | None = Field(None, alias="statusCode")


class ProAccountInfo(BaseModel):
    status: int | None
    analytics_on: bool | None = Field(None, alias="analyticsOn")
    business_suite_entrance: bool | None = Field(None, alias="businessSuiteEntrance")
    download_link: QualityFilterClass | None = Field(None, alias="downloadLink")


class BitrateSelectorConfigs(BaseModel):
    configs: list[BitrateConfigElement] | None


class CookieBanner(BaseModel):
    load_dynamically: bool | None
    decline_btn_staged_rollout_area: list[str] | None
    resource: Resource | None
    i18n: dict[str, str] | None


class DateFmtLocale(BaseModel):
    name: str | None
    months: list[str] | None
    months_short: list[str] | None = Field(None, alias="monthsShort")
    weekdays: list[str] | None
    weekdays_short: list[str] | None = Field(None, alias="weekdaysShort")
    weekdays_min: list[str] | None = Field(None, alias="weekdaysMin")
    long_date_format: dict[str, str] | None = Field(None, alias="longDateFormat")
    meridiem: Meridiem | None


class DownloadLink(BaseModel):
    microsoft: Amazon | None
    apple: Amazon | None
    amazon: Amazon | None
    google: Amazon | None


class GeoCity(BaseModel):
    city: str | None = Field(None, alias="City")
    subdivisions: str | None = Field(None, alias="Subdivisions")
    original_subdivisions: list[OriginalSubdivision] | None = Field(None, alias="OriginalSubdivisions")
    subdivisions_arr: list[str] | None = Field(None, alias="SubdivisionsArr")


class NavList(BaseModel):
    title: str | None
    children: list[Child] | None


class BizContextVideoOrder(BaseModel):
    video_order: list[VideoOrderElement] | None = Field(None, alias="videoOrder")


class ItemListVideo(BaseModel):
    list: list[str] | None
    browser_list: list[str] | None = Field(None, alias="browserList")
    loading: bool | None
    status_code: int | None = Field(None, alias="statusCode")
    has_more: bool | None = Field(None, alias="hasMore")
    cursor: int | None
    preload_list: list[PreloadList] | None = Field(None, alias="preloadList")
    keyword: str | None


class Content(BaseModel):
    desc: str | None
    text_extra: list[TextExtra] | None = Field(None, alias="textExtra")


class ImagePost(BaseModel):
    images: list[Cover] | None
    cover: Cover | None
    share_cover: Cover | None = Field(None, alias="shareCover")
    title: str | None


class BitrateInfo(BaseModel):
    gear_name: str | None = Field(None, alias="GearName")
    bitrate: int | None = Field(None, alias="Bitrate")
    quality_type: int | None = Field(None, alias="QualityType")
    play_addr: PlayAddr | None = Field(None, alias="PlayAddr")
    codec_type: str | None = Field(None, alias="CodecType")


class Abtest(BaseModel):
    page_id: str | None = Field(None, alias="pageId")
    vid_list: list | None = Field(None, alias="vidList")
    parameters: AbtestParameters | None


class ItemListElement(BaseModel):
    field_type: str | None = Field(None, alias="@type")
    position: int | None
    item: Item | None


class Users(BaseModel):
    saintajinrealmfka: Saintajinrealmfka | None


class User(BaseModel):
    ftc_user: bool | None = Field(None, alias="ftcUser")

    uid: str | None
    nick_name: str | None = Field(None, alias="nickName")
    signature: str | None
    unique_id: str | None = Field(None, alias="uniqueId")
    create_time: int | None = Field(None, alias="createTime")
    has_live_permission: bool | None = Field(None, alias="hasLivePermission")
    room_id: str | None = Field(None, alias="roomId")
    region: str | None
    avatar_uri: list[AnyUrl] | None = Field(None, alias="avatarUri")
    is_private_account: bool | None = Field(None, alias="isPrivateAccount")
    has_im_permission: bool | None = Field(None, alias="hasIMPermission")
    has_search_permission: bool | None = Field(None, alias="hasSearchPermission")
    show_private_banner: bool | None = Field(None, alias="showPrivateBanner")
    show_schedule_tips: bool | None = Field(None, alias="showScheduleTips")
    long_video_minutes: int | None = Field(None, alias="longVideoMinutes")
    age_gate_region: str | None = Field(None, alias="ageGateRegion")
    age_gate_time: str | None = Field(None, alias="ageGateTime")
    user_mode: int | None = Field(None, alias="userMode")
    has_search_live_permission: bool | None = Field(None, alias="hasSearchLivePermission")
    pro_account_info: ProAccountInfo | None = Field(None, alias="proAccountInfo")
    analytics_on: bool | None = Field(None, alias="analyticsOn")
    red_dot: list | None = Field(None, alias="redDot")
    photo_sensitive_videos_setting: int | None = Field(None, alias="photoSensitiveVideosSetting")
    has_collections_access: bool | None = Field(None, alias="hasCollectionsAccess")
    has_collections_red_dot: bool | None = Field(None, alias="hasCollectionsRedDot")
    can_exp_playlist: bool | None = Field(None, alias="canExpPlaylist")


class PurpleConfig(BaseModel):
    feature_flags: FeatureFlags | None = Field(None, alias="featureFlags")
    sign_up_open: bool | None = Field(None, alias="signUpOpen")
    cookie_banner: CookieBanner | None = Field(None, alias="cookieBanner")
    is_gray_filter: bool | None = Field(None, alias="isGrayFilter")
    nick_name_control_day: int | None = Field(None, alias="nickNameControlDay")


class ItemList(BaseModel):
    video: ItemListVideo | None


class ItemModuleVideo(BaseModel):
    id: str | None
    height: int | None
    width: int | None
    duration: int | None
    ratio: str | None
    cover: AnyUrl | None
    origin_cover: AnyUrl | None = Field(None, alias="originCover")
    dynamic_cover: str | None = Field(None, alias="dynamicCover")
    play_addr: str | None = Field(None, alias="playAddr")
    download_addr: str | None = Field(None, alias="downloadAddr")
    share_cover: list[str] | None = Field(None, alias="shareCover")
    reflow_cover: str | None = Field(None, alias="reflowCover")
    zoom_cover: dict[str, str] | None = Field(None, alias="zoomCover")
    bitrate: int | None
    encoded_type: str | None = Field(None, alias="encodedType")
    format: str | None
    video_quality: str | None = Field(None, alias="videoQuality")
    encode_user_tag: str | None = Field(None, alias="encodeUserTag")
    codec_type: str | None = Field(None, alias="codecType")
    definition: str | None
    subtitle_infos: list[SubtitleInfo] | None = Field(None, alias="subtitleInfos")
    volume_info: VolumeInfo | None = Field(None, alias="volumeInfo")
    bitrate_info: list[BitrateInfo] | None = Field(None, alias="bitrateInfo")


class JsonldListClass(BaseModel):
    item_list_element: list[ItemListElement] | None = Field(None, alias="itemListElement")


class UserModule(BaseModel):
    users: Users | None
    stats: QualityFilterClass | None


class JsonldListElement(BaseModel):
    __root__: JsonldListClass | str | None = Field(None, title="JsonldListElement")


class AppContextClass(BaseModel):
    language: str | None
    region: str | None
    app_id: int | None = Field(None, alias="appId")
    app_type: str | None = Field(None, alias="appType")
    user: User | None
    wid: str | None
    nonce: str | None
    bot_type: str | None = Field(None, alias="botType")
    request_id: str | None = Field(None, alias="requestId")
    cluster_region: str | None = Field(None, alias="clusterRegion")
    csrf_token: str | None = Field(None, alias="csrfToken")
    user_agent: str | None = Field(None, alias="userAgent")
    encrypted_webid: str | None = Field(None, alias="encryptedWebid")
    host: str | None


class BizContextClass(BaseModel):
    os: str | None
    is_mobile: bool | None = Field(None, alias="isMobile")
    is_android: bool | None = Field(None, alias="isAndroid")
    is_ios: bool | None = Field(None, alias="isIOS")
    jump_type: str | None = Field(None, alias="jumpType")
    nav_list: list[NavList] | None = Field(None, alias="navList")
    config: PurpleConfig | None
    domains: dict[str, str] | None
    download_link: DownloadLink | None = Field(None, alias="downloadLink")
    device_limit_register_expired: bool | None = Field(None, alias="deviceLimitRegisterExpired")
    subdivisions: list[str] | None
    geo: list[int] | None
    geo_city: GeoCity | None = Field(None, alias="geoCity")
    is_google_bot: bool | None = Field(None, alias="isGoogleBot")
    is_bing_bot: bool | None = Field(None, alias="isBingBot")
    is_bot: bool | None = Field(None, alias="isBot")
    is_search_engine_bot: bool | None = Field(None, alias="isSearchEngineBot")
    is_ttp: bool | None = Field(None, alias="isTTP")
    video_player_config: VideoPlayerConfig | None = Field(None, alias="videoPlayerConfig")
    playback_normalize_path: PlaybackNormalizePath | None = Field(None, alias="playbackNormalizePath")
    bitrate_config: BitrateConfigElement | None = Field(None, alias="bitrateConfig")
    search_video_for_loggedin: bool | None = Field(None, alias="searchVideoForLoggedin")

    live_suggest_config: LiveSuggestConfig | None = Field(None, alias="liveSuggestConfig")
    live_anchor_entrance: LiveAnchorEntrance | None = Field(None, alias="liveAnchorEntrance")
    live_studio_enable: bool | None = Field(None, alias="liveStudioEnable")
    xgplayer_init_host: XgplayerInitHost | None = Field(None, alias="xgplayerInitHost")
    video_order: BizContextVideoOrder | None = Field(None, alias="videoOrder")
    search_live_for_loggedin: bool | None = Field(None, alias="searchLiveForLoggedin")
    can_use_query: bool | None = Field(None, alias="canUseQuery")
    bitrate_selector_configs: BitrateSelectorConfigs | None = Field(None, alias="bitrateSelectorConfigs")


class ItemModule(BaseModel):
    id: str | None
    desc: str | None
    create_time: int | None = Field(None, alias="createTime")
    schedule_time: int | None = Field(None, alias="scheduleTime")
    video: ItemModuleVideo | None
    author: str | None
    music: Music | None
    challenges: list[Challenge] | None
    stats: ItemModuleStats | None
    warn_info: list[WarnInfo] | None = Field(None, alias="warnInfo")
    original_item: bool | None = Field(None, alias="originalItem")
    offical_item: bool | None = Field(None, alias="officalItem")
    text_extra: list[TextExtra] | None = Field(None, alias="textExtra")
    secret: bool | None
    for_friend: bool | None = Field(None, alias="forFriend")
    digged: bool | None
    item_comment_status: int | None = Field(None, alias="itemCommentStatus")
    take_down: int | None = Field(None, alias="takeDown")
    effect_stickers: list | None = Field(None, alias="effectStickers")
    private_item: bool | None = Field(None, alias="privateItem")
    duet_enabled: bool | None = Field(None, alias="duetEnabled")
    stitch_enabled: bool | None = Field(None, alias="stitchEnabled")
    stickers_on_item: list | None = Field(None, alias="stickersOnItem")
    share_enabled: bool | None = Field(None, alias="shareEnabled")
    comments: list | None
    duet_display: int | None = Field(None, alias="duetDisplay")
    stitch_display: int | None = Field(None, alias="stitchDisplay")
    index_enabled: bool | None = Field(None, alias="indexEnabled")
    image_post: ImagePost | None = Field(None, alias="imagePost")
    location_created: str | None = Field(None, alias="locationCreated")
    suggested_words: list | None = Field(None, alias="suggestedWords")
    contents: list[Content] | None
    collected: bool | None
    channel_tags: list | None = Field(None, alias="channelTags")
    nickname: str | None
    author_id: str | None = Field(None, alias="authorId")
    author_sec_id: str | None = Field(None, alias="authorSecId")
    avatar_thumb: AnyUrl | None = Field(None, alias="avatarThumb")
    download_setting: int | None = Field(None, alias="downloadSetting")
    author_private: bool | None = Field(None, alias="authorPrivate")
    capcut_anchors: list | None = Field(None, alias="capcutAnchors")
    mask_type: int | None = Field(None, alias="maskType")


class SEOState(BaseModel):
    meta_params: MetaParams | None = Field(None, alias="metaParams")
    jsonld_list: list[list[JsonldListElement]] | None = Field(None, alias="jsonldList")
    abtest: Abtest | None
    loading: bool | None
    canonical: AnyUrl | None
    page_type: int | None = Field(None, alias="pageType")
    launch_mode: str | None = Field(None, alias="launchMode")
    traffic_type: str | None = Field(None, alias="trafficType")


class AppContext(BaseModel):
    app_context: AppContextClass | None = Field(None, alias="appContext")
    initialized: bool | None
    lang: str | None
    side_nav_active: bool | None = Field(None, alias="sideNavActive")


class BizContext(BaseModel):
    biz_context: BizContextClass | None = Field(None, alias="bizContext")
    initialized: bool | None


class TiktokPageAweme(BaseModel):
    app_context: AppContext | None = Field(None, alias="AppContext")
    biz_context: BizContext | None = Field(None, alias="BizContext")
    seo_state: SEOState | None = Field(None, alias="SEOState")
    item_list: ItemList | None = Field(None, alias="ItemList")
    item_module: dict[str, ItemModule] | None = Field(None, alias="ItemModule")
    user_module: UserModule | None = Field(None, alias="UserModule")
    video_page: VideoPage | None = Field(None, alias="VideoPage")
    sharing_meta_state: SharingMetaState | None = Field(None, alias="SharingMetaState")
