# generated by datamodel-codegen:
#   timestamp: 2022-11-27T05:40:50+00:00


from __future__ import annotations

from enum import Enum

from melanie import BaseModel, Field


class TikcastRechargeStrategy(BaseModel):
    version_id: int | None


class WebappHistoryRecommend(BaseModel):
    default_select: bool | None
    not_fixed_package: bool | None


class PnsRuntimeFrameworkConfig(BaseModel):
    enabled: bool | None
    url: str | None
    url_resso: str | None
    url_ttm: str | None
    use_async: bool | None = Field(None, alias="useAsync")


class ProAccountInfoDownloadLink(BaseModel):
    pass


class BitrateConfig(BaseModel):
    bitrate_lower: int | None = Field(None, alias="bitrateLower")
    bitrate_range: list[int] | None = Field(None, alias="bitrateRange")
    bitrate_upper: int | None = Field(None, alias="bitrateUpper")
    mode: str | None
    param_bf: float | None = Field(None, alias="paramBf")
    param_bp: float | None = Field(None, alias="paramBp")
    param_lower: float | None = Field(None, alias="paramLower")
    param_upper: float | None = Field(None, alias="paramUpper")
    param_upper_bl: float | None = Field(None, alias="paramUpperBl")
    param_vl1: float | None = Field(None, alias="paramVl1")
    param_vl2: int | None = Field(None, alias="paramVl2")
    param_vl_lower: float | None = Field(None, alias="paramVlLower")
    param_vl_upper: float | None = Field(None, alias="paramVlUpper")
    sliding_window_count_threshold: int | None = Field(None, alias="slidingWindowCountThreshold")
    sliding_window_extraction: str | None = Field(None, alias="slidingWindowExtraction")
    sliding_window_type: str | None = Field(None, alias="slidingWindowType")
    sliding_window_weight: str | None = Field(None, alias="slidingWindowWeight")
    sliding_window_weight_threshold: int | None = Field(None, alias="slidingWindowWeightThreshold")


class Resource(BaseModel):
    esm: str | None
    nomodule: str | None
    version: str | None


class FeatureFlags(BaseModel):
    feature_bar: bool | None
    ftc: list[str] | None


class SgOpen(BaseModel):
    bot_threshold: int | None = Field(None, alias="BOT_THRESHOLD")
    exclude_regions: list[str] | None = Field(None, alias="EXCLUDE_REGIONS")
    sg_open: bool | None = Field(None, alias="SG_OPEN")


class Meridiem(BaseModel):
    am: str | None = Field(None, alias="AM")
    pm: str | None = Field(None, alias="PM")
    am_1: str | None = Field(None, alias="am")
    pm_1: str | None = Field(None, alias="pm")


class Amazon(BaseModel):
    normal: str | None
    visible: bool | None


class GeoCity(BaseModel):
    city: str | None = Field(None, alias="City")
    subdivisions: str | None = Field(None, alias="Subdivisions")
    subdivisions_arr: list[str] | None = Field(None, alias="SubdivisionsArr")


class LiveCenterConfig(BaseModel):
    entrance: bool | None
    show_creator_hub_region: list[str] | None = Field(None, alias="showCreatorHubRegion")


class LiveSuggestConfig(BaseModel):
    is_blocked_area: bool | None = Field(None, alias="isBlockedArea")
    is_risk_area: bool | None = Field(None, alias="isRiskArea")


class Child(BaseModel):
    href: str | None
    title: str | None
    key: str | None


class PlaybackNormalizePath(BaseModel):
    path: list[str] | None


class StudioDownloadEntrance(BaseModel):
    regions: list[str] | None


class VideoOrderElement(BaseModel):
    detail: list[int] | None
    property: str | None
    order: str | None


class VideoPlayerConfig(BaseModel):
    fallback: bool | None


class XgplayerInitHost(BaseModel):
    group1: list[str] | None
    group2: list[str] | None


class En(BaseModel):
    webapp: dict[str, str] | None = Field(None, alias="Webapp")


class PreloadList(BaseModel):
    id: str | None
    url: str | None


class AuthorStats(BaseModel):
    digg_count: int | None = Field(None, alias="diggCount")
    follower_count: int | None = Field(None, alias="followerCount")
    following_count: int | None = Field(None, alias="followingCount")
    heart: int | None
    video_count: int | None = Field(None, alias="videoCount")
    need_fix: bool | None = Field(None, alias="needFix")


class ChallengeStats(BaseModel):
    video_count: int | None = Field(None, alias="videoCount")
    view_count: int | None = Field(None, alias="viewCount")


class DuetInfo(BaseModel):
    duet_from_id: int | None = Field(None, alias="duetFromId")


class Music(BaseModel):
    album: str | None
    author_name: str | None = Field(None, alias="authorName")
    cover_large: str | None = Field(None, alias="coverLarge")
    cover_medium: str | None = Field(None, alias="coverMedium")
    cover_thumb: str | None = Field(None, alias="coverThumb")
    duration: int | None
    id: str | None
    original: bool | None
    play_url: str | None = Field(None, alias="playUrl")
    schedule_search_time: int | None = Field(None, alias="scheduleSearchTime")
    title: str | None


class ItemModuleStats(BaseModel):
    comment_count: int | None = Field(None, alias="commentCount")
    digg_count: int | None = Field(None, alias="diggCount")
    play_count: int | None = Field(None, alias="playCount")
    share_count: int | None = Field(None, alias="shareCount")


class StickersOnItem(BaseModel):
    sticker_text: list[str] | None = Field(None, alias="stickerText")
    sticker_type: int | None = Field(None, alias="stickerType")


class TextExtra(BaseModel):
    aweme_id: str | None = Field(None, alias="awemeId")
    end: int | None
    hashtag_id: int | None = Field(None, alias="hashtagId")
    hashtag_name: str | None = Field(None, alias="hashtagName")
    is_commerce: bool | None = Field(None, alias="isCommerce")

    start: int | None
    sub_type: int | None = Field(None, alias="subType")
    type: int | None
    user_id: str | None = Field(None, alias="userId")
    user_unique_id: str | None = Field(None, alias="userUniqueId")


class PlayAddr(BaseModel):
    data_size: int | None = Field(None, alias="DataSize")
    file_cs: str | None = Field(None, alias="FileCs")
    file_hash: str | None = Field(None, alias="FileHash")
    uri: str | None = Field(None, alias="Uri")
    url_key: str | None = Field(None, alias="UrlKey")
    url_list: list[str] | None = Field(None, alias="UrlList")


class VolumeInfo(BaseModel):
    loudness: float | None = Field(None, alias="Loudness")
    peak: float | None = Field(None, alias="Peak")


class RecommendUserList(BaseModel):
    unique_id: str | None = Field(None, alias="uniqueId")


class VideoDirectory(BaseModel):
    is_open: bool | None = Field(None, alias="isOpen")
    item_number: int | None = Field(None, alias="itemNumber")


class KepDirectoryVersion1(BaseModel):
    hash_size: int | None = Field(None, alias="hashSize")
    is_open: bool | None = Field(None, alias="isOpen")
    item_number: int | None = Field(None, alias="itemNumber")
    lower_limit_hash: int | None = Field(None, alias="lowerLimitHash")
    upper_limit_hash: int | None = Field(None, alias="upperLimitHash")


class KepDirectoryVersion2(BaseModel):
    bucket_size: int | None = Field(None, alias="bucketSize")
    hash_size: int | None = Field(None, alias="hashSize")
    is_open: bool | None = Field(None, alias="isOpen")
    item_number: int | None = Field(None, alias="itemNumber")
    lower_limit_hash: int | None = Field(None, alias="lowerLimitHash")
    updated_frequency_timer: int | None = Field(None, alias="updatedFrequencyTimer")
    upper_limit_hash: int | None = Field(None, alias="upperLimitHash")


class Item(BaseModel):
    _id: str | None = Field(None, alias="@id")
    _type: str | None = Field(None, alias="@type")
    name: str | None


class MetaParams(BaseModel):
    applicable_device: str | None = Field(None, alias="applicableDevice")
    canonical_href: str | None = Field(None, alias="canonicalHref")
    description: str | None
    keywords: str | None
    robots_content: str | None = Field(None, alias="robotsContent")
    title: str | None


class SharingMeta(BaseModel):
    value: dict[str, str] | None


class UserModuleStats(BaseModel):
    prettyscreams: AuthorStats | None


class CommerceUserInfo(BaseModel):
    commerce_user: bool | None = Field(None, alias="commerceUser")


class ExtraInfo(BaseModel):
    status_code: int | None = Field(None, alias="statusCode")


class ProfileTab(BaseModel):
    show_music_tab: bool | None = Field(None, alias="showMusicTab")
    show_play_list_tab: bool | None = Field(None, alias="showPlayListTab")
    show_question_tab: bool | None = Field(None, alias="showQuestionTab")


class UserPage(BaseModel):
    status_code: int | None = Field(None, alias="statusCode")
    unique_id: str | None = Field(None, alias="uniqueId")


class Vid(Enum):
    v1 = "v1"
    v2 = "v2"
    v3 = "v3"
    v7 = "v7"
    v2_1 = "V2"


class PuneHedgehog(BaseModel):
    vid: Vid | None


class DeleteWebidV2Test(BaseModel):
    generate_webid_v2: bool | None = Field(None, alias="generateWebidV2")
    vid: Vid | None


class SharingUserRedesign(BaseModel):
    bot_vid: Vid | None = Field(None, alias="botVid")
    vid: Vid | None


class Webcast(BaseModel):
    tikcast_recharge_strategy: TikcastRechargeStrategy | None
    webapp_history_recommend: WebappHistoryRecommend | None


class ProAccountInfo(BaseModel):
    analytics_on: bool | None = Field(None, alias="analyticsOn")
    business_suite_entrance: bool | None = Field(None, alias="businessSuiteEntrance")
    download_link: ProAccountInfoDownloadLink | None = Field(None, alias="downloadLink")
    status: int | None


class CookieBanner(BaseModel):
    decline_btn_staged_rollout_area: list[str] | None
    load_dynamically: bool | None
    resource: Resource | None


class DateFmtLocale(BaseModel):
    long_date_format: dict[str, str] | None = Field(None, alias="longDateFormat")
    meridiem: Meridiem | None
    months: list[str] | None
    months_short: list[str] | None = Field(None, alias="monthsShort")
    name: str | None
    weekdays: list[str] | None
    weekdays_min: list[str] | None = Field(None, alias="weekdaysMin")
    weekdays_short: list[str] | None = Field(None, alias="weekdaysShort")


class BizContextDownloadLink(BaseModel):
    amazon: Amazon | None
    apple: Amazon | None
    google: Amazon | None
    microsoft: Amazon | None


class NavList(BaseModel):
    children: list[Child] | None
    title: str | None


class BizContextVideoOrder(BaseModel):
    video_order: list[VideoOrderElement] | None = Field(None, alias="videoOrder")


class Translations(BaseModel):
    en: En | None


class UserLikedClass(BaseModel):
    browser_list: list[str] | None = Field(None, alias="browserList")
    cursor: str | None
    has_more: bool | None = Field(None, alias="hasMore")
    list: list[str] | None
    loading: bool | None
    preload_list: list[PreloadList] | None = Field(None, alias="preloadList")
    status_code: int | None = Field(None, alias="statusCode")


class Challenge(BaseModel):
    cover_larger: str | None = Field(None, alias="coverLarger")
    cover_medium: str | None = Field(None, alias="coverMedium")
    cover_thumb: str | None = Field(None, alias="coverThumb")
    desc: str | None
    id: int | None
    is_commerce: bool | None = Field(None, alias="isCommerce")
    profile_larger: str | None = Field(None, alias="profileLarger")
    profile_medium: str | None = Field(None, alias="profileMedium")
    profile_thumb: str | None = Field(None, alias="profileThumb")
    stats: ChallengeStats | None
    title: str | None


class BitrateInfo(BaseModel):
    bitrate: int | None = Field(None, alias="Bitrate")
    codec_type: str | None = Field(None, alias="CodecType")
    gear_name: str | None = Field(None, alias="GearName")
    play_addr: PlayAddr | None = Field(None, alias="PlayAddr")
    quality_type: int | None = Field(None, alias="QualityType")


class AbtestParameters(BaseModel):
    user_page_serp_compliance: PuneHedgehog | None


class Default(BaseModel):
    hashtag_video_directory: VideoDirectory | None = Field(None, alias="hashtagVideoDirectory")
    kep_directory_version1: KepDirectoryVersion1 | None = Field(None, alias="kepDirectoryVersion1")
    kep_directory_version2: KepDirectoryVersion2 | None = Field(None, alias="kepDirectoryVersion2")
    music_video_directory: VideoDirectory | None = Field(None, alias="musicVideoDirectory")
    recommend_video_directory: KepDirectoryVersion1 | None = Field(None, alias="recommendVideoDirectory")
    user_profile_directory: KepDirectoryVersion1 | None = Field(None, alias="userProfileDirectory")
    user_video_directory: VideoDirectory | None = Field(None, alias="userVideoDirectory")


class ItemListElement(BaseModel):
    _type: str | None = Field(None, alias="@type")
    item: Item | None
    position: int | None


class Prettyscreams(BaseModel):
    avatar_larger: str | None = Field(None, alias="avatarLarger")
    avatar_medium: str | None = Field(None, alias="avatarMedium")
    avatar_thumb: str | None = Field(None, alias="avatarThumb")
    comment_setting: int | None = Field(None, alias="commentSetting")
    commerce_user_info: CommerceUserInfo | None = Field(None, alias="commerceUserInfo")
    create_time: int | None = Field(None, alias="createTime")
    download_setting: int | None = Field(None, alias="downloadSetting")
    duet_setting: int | None = Field(None, alias="duetSetting")
    extra_info: ExtraInfo | None = Field(None, alias="extraInfo")
    following_visibility: int | None = Field(None, alias="followingVisibility")
    ftc: bool | None
    id: str | None
    is_ad_virtual: bool | None = Field(None, alias="isADVirtual")
    is_embed_banned: bool | None = Field(None, alias="isEmbedBanned")
    is_under_age18: bool | None = Field(None, alias="isUnderAge18")
    nick_name_modify_time: int | None = Field(None, alias="nickNameModifyTime")
    nickname: str | None
    now_invitation_card_url: str | None = Field(None, alias="nowInvitationCardUrl")
    open_favorite: bool | None = Field(None, alias="openFavorite")
    private_account: bool | None = Field(None, alias="privateAccount")
    profile_tab: ProfileTab | None = Field(None, alias="profileTab")
    recommend_reason: str | None = Field(None, alias="recommendReason")
    region: str | None
    relation: int | None
    room_id: str | None = Field(None, alias="roomId")

    secret: bool | None
    short_id: str | None = Field(None, alias="shortId")
    signature: str | None
    stitch_setting: int | None = Field(None, alias="stitchSetting")
    tt_seller: bool | None = Field(None, alias="ttSeller")
    unique_id: str | None = Field(None, alias="uniqueId")
    unique_id_modify_time: int | None = Field(None, alias="uniqueIdModifyTime")
    verified: bool | None


class User(BaseModel):
    age_gate_region: str | None = Field(None, alias="ageGateRegion")
    age_gate_time: str | None = Field(None, alias="ageGateTime")
    analytics_on: bool | None = Field(None, alias="analyticsOn")
    avatar_uri: list[str] | None = Field(None, alias="avatarUri")
    create_time: int | None = Field(None, alias="createTime")
    ftc_user: bool | None = Field(None, alias="ftcUser")
    has_collections_access: bool | None = Field(None, alias="hasCollectionsAccess")
    has_collections_red_dot: bool | None = Field(None, alias="hasCollectionsRedDot")
    has_im_permission: bool | None = Field(None, alias="hasIMPermission")
    has_live_permission: bool | None = Field(None, alias="hasLivePermission")
    is_private_account: bool | None = Field(None, alias="isPrivateAccount")
    long_video_minutes: int | None = Field(None, alias="longVideoMinutes")
    nick_name: str | None = Field(None, alias="nickName")
    photo_sensitive_videos_setting: int | None = Field(None, alias="photoSensitiveVideosSetting")
    pro_account_info: ProAccountInfo | None = Field(None, alias="proAccountInfo")
    red_dot: list | None = Field(None, alias="redDot")
    region: str | None
    room_id: str | None = Field(None, alias="roomId")

    show_private_banner: bool | None = Field(None, alias="showPrivateBanner")
    show_schedule_tips: bool | None = Field(None, alias="showScheduleTips")
    signature: str | None
    uid: str | None
    unique_id: str | None = Field(None, alias="uniqueId")
    user_mode: int | None = Field(None, alias="userMode")


class Config(BaseModel):
    cookie_banner: CookieBanner | None = Field(None, alias="cookieBanner")
    feature_flags: FeatureFlags | None = Field(None, alias="featureFlags")
    is_gray_filter: bool | None = Field(None, alias="isGrayFilter")
    nick_name_control_day: int | None = Field(None, alias="nickNameControlDay")
    sg_open: SgOpen | None = Field(None, alias="sgOpen")
    sign_up_open: bool | None = Field(None, alias="signUpOpen")


class ItemList(BaseModel):
    user_liked: UserLikedClass | None = Field(None, alias="user-liked")
    user_post: UserLikedClass | None = Field(None, alias="user-post")


class Video(BaseModel):
    bitrate: int | None
    bitrate_info: list[BitrateInfo] | None = Field(None, alias="bitrateInfo")
    codec_type: str | None = Field(None, alias="codecType")
    cover: str | None
    definition: str | None
    download_addr: str | None = Field(None, alias="downloadAddr")
    duration: int | None
    dynamic_cover: str | None = Field(None, alias="dynamicCover")
    encode_user_tag: str | None = Field(None, alias="encodeUserTag")
    encoded_type: str | None = Field(None, alias="encodedType")
    format: str | None
    height: int | None
    id: str | None
    origin_cover: str | None = Field(None, alias="originCover")
    play_addr: str | None = Field(None, alias="playAddr")
    ratio: str | None
    reflow_cover: str | None = Field(None, alias="reflowCover")
    share_cover: list[str] | None = Field(None, alias="shareCover")
    subtitle_infos: list | None = Field(None, alias="subtitleInfos")
    video_quality: str | None = Field(None, alias="videoQuality")
    volume_info: VolumeInfo | None = Field(None, alias="volumeInfo")
    width: int | None
    zoom_cover: dict[str, str] | None = Field(None, alias="zoomCover")


class Abtest(BaseModel):
    page_id: str | None = Field(None, alias="pageId")
    parameters: AbtestParameters | None
    vid_list: list[int] | None = Field(None, alias="vidList")


class DirectoryConfig(BaseModel):
    default: Default | None
    type: str | None


class JsonldListClass(BaseModel):
    item_list_element: list[ItemListElement] | None = Field(None, alias="itemListElement")
    alternate_name: str | None = Field(None, alias="alternateName")
    description: str | None
    main_entity_of_page: dict[str, str] | None = Field(None, alias="mainEntityOfPage")
    name: str | None


class Users(BaseModel):
    prettyscreams: Prettyscreams | None


class JsonldListElement(BaseModel):
    __root__: JsonldListClass | str | None = Field(None, title="JsonldListElement")


class BizContextClass(BaseModel):
    bitrate_config: BitrateConfig | None = Field(None, alias="bitrateConfig")
    config: Config | None
    date_fmt_locale: DateFmtLocale | None = Field(None, alias="dateFmtLocale")
    device_limit_register_expired: bool | None = Field(None, alias="deviceLimitRegisterExpired")
    domains: dict[str, str] | None
    download_link: BizContextDownloadLink | None = Field(None, alias="downloadLink")
    geo: list[int] | None
    geo_city: GeoCity | None = Field(None, alias="geoCity")
    is_android: bool | None = Field(None, alias="isAndroid")
    is_bing_bot: bool | None = Field(None, alias="isBingBot")
    is_bot: bool | None = Field(None, alias="isBot")
    is_google_bot: bool | None = Field(None, alias="isGoogleBot")
    is_ios: bool | None = Field(None, alias="isIOS")
    is_mobile: bool | None = Field(None, alias="isMobile")
    is_search_engine_bot: bool | None = Field(None, alias="isSearchEngineBot")
    is_ttp: bool | None = Field(None, alias="isTTP")
    jump_type: str | None = Field(None, alias="jumpType")
    live_center_config: LiveCenterConfig | None = Field(None, alias="liveCenterConfig")
    live_studio_enable: bool | None = Field(None, alias="liveStudioEnable")
    live_suggest_config: LiveSuggestConfig | None = Field(None, alias="liveSuggestConfig")
    nav_list: list[NavList] | None = Field(None, alias="navList")
    os: str | None
    playback_normalize_path: PlaybackNormalizePath | None = Field(None, alias="playbackNormalizePath")
    search_video_for_loggedin: bool | None = Field(None, alias="searchVideoForLoggedin")
    studio_download_entrance: StudioDownloadEntrance | None = Field(None, alias="studioDownloadEntrance")
    subdivisions: list[str] | None
    video_order: BizContextVideoOrder | None = Field(None, alias="videoOrder")
    video_player_config: VideoPlayerConfig | None = Field(None, alias="videoPlayerConfig")
    xgplayer_init_host: XgplayerInitHost | None = Field(None, alias="xgplayerInitHost")


class ItemModule(BaseModel):
    ad_authorization: bool | None = Field(None, alias="adAuthorization")
    ad_label_version: int | None = Field(None, alias="adLabelVersion")
    author: str | None
    author_id: str | None = Field(None, alias="authorId")
    author_private: bool | None = Field(None, alias="authorPrivate")
    author_sec_id: str | None = Field(None, alias="authorSecId")
    author_stats: AuthorStats | None = Field(None, alias="authorStats")
    avatar_thumb: str | None = Field(None, alias="avatarThumb")
    challenges: list[Challenge] | None
    comments: list | None
    create_time: int | None = Field(None, alias="createTime")
    desc: str | None
    digged: bool | None
    download_setting: int | None = Field(None, alias="downloadSetting")
    duet_display: int | None = Field(None, alias="duetDisplay")
    duet_enabled: bool | None = Field(None, alias="duetEnabled")
    duet_info: DuetInfo | None = Field(None, alias="duetInfo")
    effect_stickers: list | None = Field(None, alias="effectStickers")
    for_friend: bool | None = Field(None, alias="forFriend")
    id: str | None
    index_enabled: bool | None = Field(None, alias="indexEnabled")
    is_ad: bool | None = Field(None, alias="isAd")
    item_comment_status: int | None = Field(None, alias="itemCommentStatus")
    item_mute: bool | None = Field(None, alias="itemMute")
    location_created: str | None = Field(None, alias="locationCreated")
    music: Music | None
    nickname: str | None
    offical_item: bool | None = Field(None, alias="officalItem")
    original_item: bool | None = Field(None, alias="originalItem")
    private_item: bool | None = Field(None, alias="privateItem")
    schedule_time: int | None = Field(None, alias="scheduleTime")
    secret: bool | None
    share_enabled: bool | None = Field(None, alias="shareEnabled")
    show_not_pass: bool | None = Field(None, alias="showNotPass")
    stats: ItemModuleStats | None
    stickers_on_item: list[StickersOnItem] | None = Field(None, alias="stickersOnItem")
    stitch_display: int | None = Field(None, alias="stitchDisplay")
    stitch_enabled: bool | None = Field(None, alias="stitchEnabled")
    take_down: int | None = Field(None, alias="takeDown")
    text_extra: list[TextExtra] | None = Field(None, alias="textExtra")
    video: Video | None
    vl1: bool | None
    warn_info: list | None = Field(None, alias="warnInfo")


class SEO(BaseModel):
    abtest: Abtest | None
    canonical: str | None
    directory_config: DirectoryConfig | None = Field(None, alias="directoryConfig")
    jsonld_list: list[list[JsonldListElement]] | None = Field(None, alias="jsonldList")
    launch_mode: str | None = Field(None, alias="launchMode")
    loading: bool | None
    meta_params: MetaParams | None = Field(None, alias="metaParams")
    page_type: int | None = Field(None, alias="pageType")


class UserModule(BaseModel):
    stats: UserModuleStats | None
    users: Users | None


class AppContextClass(BaseModel):
    app_id: int | None = Field(None, alias="appId")
    app_type: str | None = Field(None, alias="appType")
    bot_type: str | None = Field(None, alias="botType")
    cluster_region: str | None = Field(None, alias="clusterRegion")
    csrf_token: str | None = Field(None, alias="csrfToken")
    encrypted_webid: str | None = Field(None, alias="encryptedWebid")
    host: str | None
    is_downgraded_to_csr: bool | None = Field(None, alias="isDowngradedToCSR")
    is_sg_open_exclude_regions: bool | None = Field(None, alias="isSgOpenExcludeRegions")
    language: str | None
    nonce: str | None
    pns_runtime_framework_config: PnsRuntimeFrameworkConfig | None = Field(None, alias="pnsRuntimeFrameworkConfig")
    region: str | None
    request_id: str | None = Field(None, alias="requestId")
    sg_open: bool | None = Field(None, alias="sgOpen")
    user: User | None
    user_agent: str | None = Field(None, alias="userAgent")
    wid: str | None


class BizContext(BaseModel):
    biz_context: BizContextClass | None = Field(None, alias="bizContext")
    initialized: bool | None


class AppContext(BaseModel):
    app_context: AppContextClass | None = Field(None, alias="appContext")
    initialized: bool | None
    is_downgraded_to_csr: bool | None = Field(None, alias="isDowngradedToCSR")
    lang: str | None
    side_nav_active: bool | None = Field(None, alias="sideNavActive")


class TiktokSIGI_STATE(BaseModel):
    app_context: AppContext | None = Field(None, alias="AppContext")
    biz_context: BizContext | None = Field(None, alias="BizContext")
    item_list: ItemList | None = Field(None, alias="ItemList")
    item_module: dict[str, ItemModule] | None = Field(None, alias="ItemModule")
    recommend_user_list: RecommendUserList | None = Field(None, alias="RecommendUserList")
    seo: SEO | None = Field(None, alias="SEO")
    sharing_meta: SharingMeta | None = Field(None, alias="SharingMeta")
    user_module: UserModule | None = Field(None, alias="UserModule")
    user_page: UserPage | None = Field(None, alias="UserPage")
