# generated by datamodel-codegen:
#   timestamp: 2022-12-06T09:57:27+00:00


from __future__ import annotations

from datetime import date  # noqa
from typing import Any

from melanie import BaseModel


class Metadata(BaseModel):
    pass


class SourceTypes(BaseModel):
    card: int | None


class Address(BaseModel):
    country: str | None
    postal_code: str | None
    city: str | None
    line1: str | None
    line2: Any | None
    state: str | None


class FraudDetails(BaseModel):
    stripe_report: str | None


class Outcome(BaseModel):
    network_status: str | None
    reason: str | None
    risk_level: str | None
    risk_score: int | None
    seller_message: str | None
    type: str | None
    rule: str | None


class Checks(BaseModel):
    address_line1_check: Any | None
    address_postal_code_check: str | None
    cvc_check: str | None


class ThreeDSecure(BaseModel):
    authenticated: bool | None
    authentication_flow: str | None
    result: str | None
    succeeded: bool | None
    version: str | None


class Shipping(BaseModel):
    address: Address | None
    carrier: Any | None
    name: str | None
    phone: Any | None
    tracking_number: Any | None


class IssuingAvailable(BaseModel):
    amount: int | None
    currency: str | None


class PaymentMethodOptionsCard(BaseModel):
    installments: Any | None
    mandate_options: Any | None
    network: Any | None
    request_three_d_secure: str | None


class Request(BaseModel):
    idempotency_key: str | None
    id: str | None


class AmountDetails(BaseModel):
    tip: Metadata | None


class PendingElement(BaseModel):
    amount: int | None
    currency: str | None
    source_types: SourceTypes | None


class BillingDetails(BaseModel):
    address: Address | None
    email: str | None
    name: str | None
    phone: Any | None


class PaymentMethodDetailsCard(BaseModel):
    brand: str | None
    checks: Checks | None
    country: str | None
    exp_month: int | None
    exp_year: int | None
    fingerprint: str | None
    funding: str | None
    installments: Any | None
    last4: int | None
    mandate: Any | None
    network: str | None
    three_d_secure: ThreeDSecure | None
    wallet: Any | None


class Issuing(BaseModel):
    available: list[IssuingAvailable] | None


class PaymentMethodOptions(BaseModel):
    card: PaymentMethodOptionsCard | None


class PaymentMethodDetails(BaseModel):
    card: PaymentMethodDetailsCard | None
    type: str | None


class StripeWebhookPayload(BaseModel):
    api_version: date | None
    created: int | None
    data: Data | None
    id: str | None
    livemode: bool | None
    object: str | None
    pending_webhooks: int | None
    type: str | None
    request: Request | None


class Data(BaseModel):
    object: Object | None


class Object(BaseModel):
    available: list[PendingElement] | None
    issuing: Issuing | None
    livemode: bool | None
    object: str | None
    pending: list[PendingElement] | None
    amount: int | None
    amount_captured: int | None
    amount_refunded: int | None
    billing_details: BillingDetails | None
    captured: bool | None
    created: int | None
    currency: str | None
    disputed: bool | None
    failure_code: str | None
    failure_message: str | None
    fraud_details: FraudDetails | None
    id: str | None
    outcome: Outcome | None
    paid: bool | None
    payment_intent: str | None
    payment_method: str | None
    payment_method_details: PaymentMethodDetails | None
    receipt_email: str | None
    refunded: bool | None
    refunds: Charges | None
    status: str | None
    amount_updates: list | None
    application: Any | None
    application_fee: Any | None
    application_fee_amount: Any | None
    balance_transaction: str | None
    calculated_statement_descriptor: str | None
    customer: Any | None
    description: str | None
    destination: Any | None
    dispute: Any | None
    failure_balance_transaction: Any | None
    invoice: Any | None
    metadata: Metadata | None
    on_behalf_of: Any | None
    order: Any | None
    receipt_number: Any | None
    receipt_url: str | None
    review: Any | None
    shipping: Shipping | None
    source: Any | None
    source_transfer: Any | None
    statement_descriptor: Any | None
    statement_descriptor_suffix: Any | None
    transfer_data: Any | None
    transfer_group: Any | None
    amount_capturable: int | None
    amount_details: AmountDetails | None
    amount_received: int | None
    automatic_payment_methods: Any | None
    canceled_at: int | None
    cancellation_reason: str | None
    capture_method: str | None
    charges: Charges | None
    client_secret: str | None
    confirmation_method: str | None
    last_payment_error: Any | None
    next_action: Any | None
    payment_method_options: PaymentMethodOptions | None
    payment_method_types: list[str] | None
    processing: Any | None
    setup_future_usage: Any | None


class Charges(BaseModel):
    data: list[Datum] | None
    has_more: bool | None
    object: str | None
    total_count: int | None
    url: str | None


class Datum(BaseModel):
    amount: int | None
    amount_captured: int | None
    amount_refunded: int | None
    amount_updates: list | None
    application: Any | None
    application_fee: Any | None
    application_fee_amount: Any | None
    balance_transaction: str | None
    billing_details: BillingDetails | None
    calculated_statement_descriptor: str | None
    captured: bool | None
    created: int | None
    currency: str | None
    customer: Any | None
    description: str | None
    destination: Any | None
    dispute: Any | None
    disputed: bool | None
    failure_balance_transaction: Any | None
    failure_code: str | None
    failure_message: str | None
    fraud_details: FraudDetails | None
    id: str | None
    invoice: Any | None
    livemode: bool | None
    metadata: Metadata | None
    object: str | None
    on_behalf_of: Any | None
    order: Any | None
    outcome: Outcome | None
    paid: bool | None
    payment_intent: str | None
    payment_method: str | None
    payment_method_details: PaymentMethodDetails | None
    receipt_email: str | None
    receipt_number: Any | None
    receipt_url: str | None
    refunded: bool | None
    refunds: Charges | None
    review: Any | None
    shipping: Shipping | None
    source: Any | None
    source_transfer: Any | None
    statement_descriptor: Any | None
    statement_descriptor_suffix: Any | None
    status: str | None
    transfer_data: Any | None
    transfer_group: Any | None


StripeWebhookPayload.update_forward_refs()
Data.update_forward_refs()
Object.update_forward_refs()
Charges.update_forward_refs()
