# generated by datamodel-codegen:
#   timestamp: 2023-07-07T09:32:31+00:00

from __future__ import annotations

from melanie import AnyUrl, BaseModel, Field


class Caption(BaseModel):
    text: str | None


class PurpleCandidate(BaseModel):
    url: AnyUrl | None


class FluffyCandidate(BaseModel):
    height: int | None
    url: AnyUrl | None
    width: int | None
    field__typename: str | None = Field(None, alias="__typename")


class ReplyToAuthor(BaseModel):
    username: str | None
    id: str | None


class User(BaseModel):
    profile_pic_url: AnyUrl | None
    username: str | None
    id: str | None
    is_verified: bool | None
    pk: str | None


class VideoVersion(BaseModel):
    type: int | None
    url: AnyUrl | None
    field__typename: str | None = Field(None, alias="__typename")


class ReplyFacepileUser(BaseModel):
    field__typename: str | None = Field(None, alias="__typename")
    id: str | None
    profile_pic_url: AnyUrl | None


class Extensions(BaseModel):
    is_final: bool | None


class CarouselMediaImageVersions2(BaseModel):
    candidates: list[PurpleCandidate] | None


class PurpleImageVersions2(BaseModel):
    candidates: list[FluffyCandidate] | None


class TextPostAppInfo(BaseModel):
    reply_to_author: ReplyToAuthor | None
    is_post_unavailable: bool | None
    direct_reply_count: int | None


class FluffyPost(BaseModel):
    user: User | None
    image_versions2: CarouselMediaImageVersions2 | None
    original_width: int | None
    original_height: int | None
    video_versions: list | None

    pk: str | None

    text_post_app_info: TextPostAppInfo | None
    caption: Caption | None
    taken_at: int | None
    like_count: int | None
    code: str | None

    id: str | None


class CarouselMedia(BaseModel):
    image_versions2: CarouselMediaImageVersions2 | None
    video_versions: list | None
    has_audio: bool | None
    original_height: int | None
    original_width: int | None
    pk: str | None
    id: str | None


class ReplyThreadThreadItem(BaseModel):
    post: FluffyPost | None
    line_type: str | None
    view_replies_cta_string: str | None
    reply_facepile_users: list[ReplyFacepileUser] | None
    should_show_replies_cta: bool | None


class PurplePost(BaseModel):
    user: User | None
    image_versions2: PurpleImageVersions2 | None
    original_width: int | None
    original_height: int | None
    video_versions: list[VideoVersion] | None
    carousel_media: list[CarouselMedia] | None
    carousel_media_count: int | None
    pk: str | None
    has_audio: bool | None
    text_post_app_info: TextPostAppInfo | None
    caption: Caption | None
    taken_at: int | None
    like_count: int | None
    code: str | None
    id: str | None


class ReplyThread(BaseModel):
    thread_items: list[ReplyThreadThreadItem] | None
    thread_type: str | None
    id: str | None


class ContainingThreadThreadItem(BaseModel):
    post: PurplePost | None
    line_type: str | None
    view_replies_cta_string: str | None
    reply_facepile_users: list | None
    should_show_replies_cta: bool | None


class ContainingThread(BaseModel):
    thread_items: list[ContainingThreadThreadItem] | None
    thread_type: str | None
    id: str | None


class DataData(BaseModel):
    containing_thread: ContainingThread | None
    reply_threads: list[ReplyThread] | None


class TopLevelData(BaseModel):
    data: DataData | None


class ThreadsDataRaw(BaseModel):
    data: TopLevelData | None
    extensions: Extensions | None
