# generated by datamodel-codegen:
#   timestamp: 2023-01-20T18:09:47+00:00


from __future__ import annotations

import orjson
from bs4 import BeautifulSoup
from bs4.element import Tag  # noqa

from melanie import BaseModel, Field
from runtimeopt.offloaded import offloaded


@offloaded
def extract_sigi_state(data) -> bytes:
    soup = BeautifulSoup(data, "lxml")
    for x in soup.find_all("script", type="application/json", id="SIGI_STATE"):
        return orjson.dumps(orjson.loads(x.decode_contents()))
    return None


class UserPageSerpCompliance(BaseModel):
    vid: str | None


class PnsRuntimeFrameworkConfig(BaseModel):
    url: str | None
    url_ttm: str | None
    url_resso: str | None
    enabled: bool | None
    use_async: bool | None = Field(None, alias="useAsync")


class ProAccountInfoDownloadLink(BaseModel):
    pass


class BitrateConfig(BaseModel):
    bitrate_lower: int | None = Field(None, alias="bitrateLower")
    bitrate_range: list[int] | None = Field(None, alias="bitrateRange")
    bitrate_upper: int | None = Field(None, alias="bitrateUpper")
    mode: str | None
    param_bf: float | None = Field(None, alias="paramBf")
    param_bp: float | None = Field(None, alias="paramBp")
    param_lower: float | None = Field(None, alias="paramLower")
    param_upper: float | None = Field(None, alias="paramUpper")
    param_upper_bl: float | None = Field(None, alias="paramUpperBl")
    param_vl1: float | None = Field(None, alias="paramVl1")
    param_vl2: int | None = Field(None, alias="paramVl2")
    param_vl_lower: float | None = Field(None, alias="paramVlLower")
    param_vl_upper: float | None = Field(None, alias="paramVlUpper")
    sliding_window_count_threshold: int | None = Field(None, alias="slidingWindowCountThreshold")
    sliding_window_extraction: str | None = Field(None, alias="slidingWindowExtraction")
    sliding_window_type: str | None = Field(None, alias="slidingWindowType")
    sliding_window_weight: str | None = Field(None, alias="slidingWindowWeight")
    sliding_window_weight_threshold: int | None = Field(None, alias="slidingWindowWeightThreshold")


class Resource(BaseModel):
    prefix: str | None
    themes: list[str] | None
    esm: str | None
    nomodule: str | None
    version: str | None


class FeatureFlags(BaseModel):
    ftc: list[str] | None
    feature_bar: bool | None


class Meridiem(BaseModel):
    am: str | None
    pm: str | None
    am_1: str | None = Field(None, alias="AM")
    pm_1: str | None = Field(None, alias="PM")


class Amazon(BaseModel):
    visible: bool | None
    normal: str | None


class GeoCity(BaseModel):
    city: str | None = Field(None, alias="City")
    subdivisions: str | None = Field(None, alias="Subdivisions")
    subdivisions_arr: list[str] | None = Field(None, alias="SubdivisionsArr")


class LiveCenterConfig(BaseModel):
    entrance: bool | None
    show_creator_hub_region: list[str] | None = Field(None, alias="showCreatorHubRegion")


class LiveSuggestConfig(BaseModel):
    is_blocked_area: bool | None = Field(None, alias="isBlockedArea")
    is_risk_area: bool | None = Field(None, alias="isRiskArea")


class Child(BaseModel):
    title: str | None
    href: str | None
    key: str | None


class PlaybackNormalizePath(BaseModel):
    path: list[str] | None


class StudioDownloadEntrance(BaseModel):
    regions: list[str] | None
    user_regions: list[str] | None = Field(None, alias="userRegions")
    all_regions: bool | None = Field(None, alias="allRegions")


class VideoOrderElement(BaseModel):
    property: str | None
    detail: list[int] | None
    order: str | None


class VideoPlayerConfig(BaseModel):
    fallback: bool | None


class XgplayerInitHost(BaseModel):
    group1: list[str] | None
    group2: list[str] | None


class PreloadList(BaseModel):
    url: str | None
    id: str | None


class AuthorStats(BaseModel):
    follower_count: int | None = Field(None, alias="followerCount")
    following_count: int | None = Field(None, alias="followingCount")
    heart: int | None
    heart_count: int | None = Field(None, alias="heartCount")
    video_count: int | None = Field(None, alias="videoCount")
    digg_count: int | None = Field(None, alias="diggCount")
    need_fix: bool | None = Field(None, alias="needFix")


class ChallengeStats(BaseModel):
    video_count: int | None = Field(None, alias="videoCount")
    view_count: int | None = Field(None, alias="viewCount")


class DuetInfo(BaseModel):
    duet_from_id: str | None = Field(None, alias="duetFromId")


class EffectSticker(BaseModel):
    name: str | None
    id: int | None = Field(None, alias="ID")


class Music(BaseModel):
    id: str | None
    title: str | None
    play_url: str | None = Field(None, alias="playUrl")
    cover_large: str | None = Field(None, alias="coverLarge")
    cover_medium: str | None = Field(None, alias="coverMedium")
    cover_thumb: str | None = Field(None, alias="coverThumb")
    author_name: str | None = Field(None, alias="authorName")
    original: bool | None
    duration: int | None
    album: str | None
    schedule_search_time: int | None = Field(None, alias="scheduleSearchTime")


class ItemModuleStats(BaseModel):
    digg_count: int | None = Field(None, alias="diggCount")
    share_count: int | None = Field(None, alias="shareCount")
    comment_count: int | None = Field(None, alias="commentCount")
    play_count: int | None = Field(None, alias="playCount")


class StickersOnItem(BaseModel):
    sticker_text: list[str] | None = Field(None, alias="stickerText")
    sticker_type: int | None = Field(None, alias="stickerType")


class TextExtra(BaseModel):
    aweme_id: str | None = Field(None, alias="awemeId")
    start: int | None
    end: int | None
    hashtag_id: str | None = Field(None, alias="hashtagId")
    hashtag_name: str | None = Field(None, alias="hashtagName")
    type: int | None
    sub_type: int | None = Field(None, alias="subType")
    user_id: str | None = Field(None, alias="userId")
    is_commerce: bool | None = Field(None, alias="isCommerce")
    user_unique_id: str | None = Field(None, alias="userUniqueId")


class PlayAddr(BaseModel):
    uri: str | None = Field(None, alias="Uri")
    url_list: list[str] | None = Field(None, alias="UrlList")
    data_size: int | None = Field(None, alias="DataSize")
    url_key: str | None = Field(None, alias="UrlKey")
    file_hash: str | None = Field(None, alias="FileHash")
    file_cs: str | None = Field(None, alias="FileCs")


class VolumeInfo(BaseModel):
    loudness: float | None = Field(None, alias="Loudness")
    peak: float | None = Field(None, alias="Peak")


class RecommendUserList(BaseModel):
    unique_id: str | None = Field(None, alias="uniqueId")


class Parameters(BaseModel):
    user_page_serp_compliance: UserPageSerpCompliance | None


class VideoDirectory(BaseModel):
    is_open: bool | None = Field(None, alias="isOpen")
    item_number: int | None = Field(None, alias="itemNumber")


class KepDirectoryVersion1(BaseModel):
    is_open: bool | None = Field(None, alias="isOpen")
    item_number: int | None = Field(None, alias="itemNumber")
    hash_size: int | None = Field(None, alias="hashSize")
    upper_limit_hash: int | None = Field(None, alias="upperLimitHash")
    lower_limit_hash: int | None = Field(None, alias="lowerLimitHash")


class KepDirectoryVersion2(BaseModel):
    is_open: bool | None = Field(None, alias="isOpen")
    item_number: int | None = Field(None, alias="itemNumber")
    hash_size: int | None = Field(None, alias="hashSize")
    bucket_size: int | None = Field(None, alias="bucketSize")
    upper_limit_hash: int | None = Field(None, alias="upperLimitHash")
    lower_limit_hash: int | None = Field(None, alias="lowerLimitHash")
    updated_frequency_timer: int | None = Field(None, alias="updatedFrequencyTimer")


class Item(BaseModel):
    field_type: str | None = Field(None, alias="@type")
    field_id: str | None = Field(None, alias="@id")
    name: str | None


class MetaParams(BaseModel):
    title: str | None
    description: str | None
    canonical_href: str | None = Field(None, alias="canonicalHref")
    robots_content: str | None = Field(None, alias="robotsContent")
    applicable_device: str | None = Field(None, alias="applicableDevice")


class SharingMeta(BaseModel):
    value: dict[str, str] | None


class CommerceUserInfo(BaseModel):
    commerce_user: bool | None = Field(None, alias="commerceUser")


class ExtraInfo(BaseModel):
    status_code: int | None = Field(None, alias="statusCode")


class ProfileTab(BaseModel):
    show_music_tab: bool | None = Field(None, alias="showMusicTab")
    show_question_tab: bool | None = Field(None, alias="showQuestionTab")
    show_play_list_tab: bool | None = Field(None, alias="showPlayListTab")


class UserPage(BaseModel):
    unique_id: str | None = Field(None, alias="uniqueId")
    status_code: int | None = Field(None, alias="statusCode")


class ProAccountInfo(BaseModel):
    status: int | None
    analytics_on: bool | None = Field(None, alias="analyticsOn")
    business_suite_entrance: bool | None = Field(None, alias="businessSuiteEntrance")
    download_link: ProAccountInfoDownloadLink | None = Field(None, alias="downloadLink")


class CookieBanner(BaseModel):
    load_dynamically: bool | None
    decline_btn_staged_rollout_area: list[str] | None
    resource: Resource | None
    i18n: dict[str, str] | None


class DateFmtLocale(BaseModel):
    name: str | None
    months: list[str] | None
    months_short: list[str] | None = Field(None, alias="monthsShort")
    weekdays: list[str] | None
    weekdays_short: list[str] | None = Field(None, alias="weekdaysShort")
    weekdays_min: list[str] | None = Field(None, alias="weekdaysMin")
    long_date_format: dict[str, str] | None = Field(None, alias="longDateFormat")
    meridiem: Meridiem | None


class BizContextDownloadLink(BaseModel):
    microsoft: Amazon | None
    apple: Amazon | None
    amazon: Amazon | None
    google: Amazon | None


class NavList(BaseModel):
    title: str | None
    children: list[Child] | None


class BizContextVideoOrder(BaseModel):
    video_order: list[VideoOrderElement] | None = Field(None, alias="videoOrder")


class UserLikedClass(BaseModel):
    list: list[str] | None
    browser_list: list[str] | None = Field(None, alias="browserList")
    loading: bool | None
    status_code: int | None = Field(None, alias="statusCode")
    has_more: bool | None = Field(None, alias="hasMore")
    cursor: str | None
    preload_list: list[PreloadList] | None = Field(None, alias="preloadList")


class Challenge(BaseModel):
    id: int | None
    title: str | None
    desc: str | None
    profile_larger: str | None = Field(None, alias="profileLarger")
    profile_medium: str | None = Field(None, alias="profileMedium")
    profile_thumb: str | None = Field(None, alias="profileThumb")
    cover_larger: str | None = Field(None, alias="coverLarger")
    cover_medium: str | None = Field(None, alias="coverMedium")
    cover_thumb: str | None = Field(None, alias="coverThumb")
    is_commerce: bool | None = Field(None, alias="isCommerce")
    stats: ChallengeStats | None


class BitrateInfo(BaseModel):
    gear_name: str | None = Field(None, alias="GearName")
    bitrate: int | None = Field(None, alias="Bitrate")
    quality_type: int | None = Field(None, alias="QualityType")
    play_addr: PlayAddr | None = Field(None, alias="PlayAddr")
    codec_type: str | None = Field(None, alias="CodecType")


class Abtest(BaseModel):
    page_id: str | None = Field(None, alias="pageId")
    vid_list: list | None = Field(None, alias="vidList")
    parameters: Parameters | None


class Default(BaseModel):
    kep_directory_version1: KepDirectoryVersion1 | None = Field(None, alias="kepDirectoryVersion1")
    kep_directory_version2: KepDirectoryVersion2 | None = Field(None, alias="kepDirectoryVersion2")
    user_profile_directory: KepDirectoryVersion1 | None = Field(None, alias="userProfileDirectory")
    recommend_video_directory: KepDirectoryVersion1 | None = Field(None, alias="recommendVideoDirectory")
    user_video_directory: VideoDirectory | None = Field(None, alias="userVideoDirectory")
    music_video_directory: VideoDirectory | None = Field(None, alias="musicVideoDirectory")
    hashtag_video_directory: VideoDirectory | None = Field(None, alias="hashtagVideoDirectory")


class ItemListElement(BaseModel):
    field_type: str | None = Field(None, alias="@type")
    position: int | None
    item: Item | None


class UserModuleItem(BaseModel):
    id: str | None
    short_id: str | None = Field(None, alias="shortId")
    unique_id: str | None = Field(None, alias="uniqueId")
    nickname: str | None
    avatar_larger: str | None = Field(None, alias="avatarLarger")
    avatar_medium: str | None = Field(None, alias="avatarMedium")
    avatar_thumb: str | None = Field(None, alias="avatarThumb")
    signature: str | None
    create_time: int | None = Field(None, alias="createTime")
    verified: bool | None
    ftc: bool | None
    relation: int | None
    open_favorite: bool | None = Field(None, alias="openFavorite")
    comment_setting: int | None = Field(None, alias="commentSetting")
    commerce_user_info: CommerceUserInfo | None = Field(None, alias="commerceUserInfo")
    duet_setting: int | None = Field(None, alias="duetSetting")
    stitch_setting: int | None = Field(None, alias="stitchSetting")
    private_account: bool | None = Field(None, alias="privateAccount")
    secret: bool | None
    is_ad_virtual: bool | None = Field(None, alias="isADVirtual")
    room_id: str | None = Field(None, alias="roomId")
    unique_id_modify_time: int | None = Field(None, alias="uniqueIdModifyTime")
    tt_seller: bool | None = Field(None, alias="ttSeller")
    region: str | None
    download_setting: int | None = Field(None, alias="downloadSetting")
    profile_tab: ProfileTab | None = Field(None, alias="profileTab")
    following_visibility: int | None = Field(None, alias="followingVisibility")
    recommend_reason: str | None = Field(None, alias="recommendReason")
    now_invitation_card_url: str | None = Field(None, alias="nowInvitationCardUrl")
    nick_name_modify_time: int | None = Field(None, alias="nickNameModifyTime")
    is_embed_banned: bool | None = Field(None, alias="isEmbedBanned")
    profile_embed_permission: int | None = Field(None, alias="profileEmbedPermission")
    extra_info: ExtraInfo | None = Field(None, alias="extraInfo")


class User(BaseModel):
    ftc_user: bool | None = Field(None, alias="ftcUser")
    uid: str | None
    nick_name: str | None = Field(None, alias="nickName")
    signature: str | None
    unique_id: str | None = Field(None, alias="uniqueId")
    create_time: int | None = Field(None, alias="createTime")
    has_live_permission: bool | None = Field(None, alias="hasLivePermission")
    room_id: str | None = Field(None, alias="roomId")
    region: str | None
    avatar_uri: list[str] | None = Field(None, alias="avatarUri")
    is_private_account: bool | None = Field(None, alias="isPrivateAccount")
    has_im_permission: bool | None = Field(None, alias="hasIMPermission")
    show_private_banner: bool | None = Field(None, alias="showPrivateBanner")
    show_schedule_tips: bool | None = Field(None, alias="showScheduleTips")
    long_video_minutes: int | None = Field(None, alias="longVideoMinutes")
    age_gate_region: str | None = Field(None, alias="ageGateRegion")
    age_gate_time: str | None = Field(None, alias="ageGateTime")
    user_mode: int | None = Field(None, alias="userMode")
    pro_account_info: ProAccountInfo | None = Field(None, alias="proAccountInfo")
    analytics_on: bool | None = Field(None, alias="analyticsOn")
    red_dot: list | None = Field(None, alias="redDot")
    photo_sensitive_videos_setting: int | None = Field(None, alias="photoSensitiveVideosSetting")
    has_collections_access: bool | None = Field(None, alias="hasCollectionsAccess")
    has_collections_red_dot: bool | None = Field(None, alias="hasCollectionsRedDot")


class Config(BaseModel):
    feature_flags: FeatureFlags | None = Field(None, alias="featureFlags")
    sign_up_open: bool | None = Field(None, alias="signUpOpen")
    cookie_banner: CookieBanner | None = Field(None, alias="cookieBanner")
    is_gray_filter: bool | None = Field(None, alias="isGrayFilter")
    nick_name_control_day: int | None = Field(None, alias="nickNameControlDay")


class ItemList(BaseModel):
    user_post: UserLikedClass | None = Field(None, alias="user-post")
    user_liked: UserLikedClass | None = Field(None, alias="user-liked")


class Video(BaseModel):
    id: str | None
    height: int | None
    width: int | None
    duration: int | None
    ratio: str | None
    cover: str | None
    origin_cover: str | None = Field(None, alias="originCover")
    dynamic_cover: str | None = Field(None, alias="dynamicCover")
    play_addr: str | None = Field(None, alias="playAddr")
    download_addr: str | None = Field(None, alias="downloadAddr")
    share_cover: list[str] | None = Field(None, alias="shareCover")
    reflow_cover: str | None = Field(None, alias="reflowCover")
    bitrate: int | None
    encoded_type: str | None = Field(None, alias="encodedType")
    format: str | None
    video_quality: str | None = Field(None, alias="videoQuality")
    encode_user_tag: str | None = Field(None, alias="encodeUserTag")
    codec_type: str | None = Field(None, alias="codecType")
    definition: str | None
    subtitle_infos: list | None = Field(None, alias="subtitleInfos")
    zoom_cover: dict[str, str] | None = Field(None, alias="zoomCover")
    volume_info: VolumeInfo | None = Field(None, alias="volumeInfo")
    bitrate_info: list[BitrateInfo] | None = Field(None, alias="bitrateInfo")


class DirectoryConfig(BaseModel):
    type: str | None
    default: Default | None


class JsonldListClass(BaseModel):
    item_list_element: list[ItemListElement] | None = Field(None, alias="itemListElement")
    name: str | None
    description: str | None
    alternate_name: str | None = Field(None, alias="alternateName")
    main_entity_of_page: dict[str, str] | None = Field(None, alias="mainEntityOfPage")


class JsonldListElement(BaseModel):
    __root__: JsonldListClass | str | None = Field(None, title="JsonldListElement")


class AppContextClass(BaseModel):
    is_downgraded_to_csr: bool | None = Field(None, alias="isDowngradedToCSR")
    language: str | None
    region: str | None
    app_id: int | None = Field(None, alias="appId")
    app_type: str | None = Field(None, alias="appType")
    user: User | None
    wid: str | None
    nonce: str | None
    bot_type: str | None = Field(None, alias="botType")
    request_id: str | None = Field(None, alias="requestId")
    cluster_region: str | None = Field(None, alias="clusterRegion")
    csrf_token: str | None = Field(None, alias="csrfToken")
    user_agent: str | None = Field(None, alias="userAgent")
    encrypted_webid: str | None = Field(None, alias="encryptedWebid")
    host: str | None
    pns_runtime_framework_config: PnsRuntimeFrameworkConfig | None = Field(None, alias="pnsRuntimeFrameworkConfig")


class BizContextClass(BaseModel):
    os: str | None
    is_mobile: bool | None = Field(None, alias="isMobile")
    is_android: bool | None = Field(None, alias="isAndroid")
    is_ios: bool | None = Field(None, alias="isIOS")
    jump_type: str | None = Field(None, alias="jumpType")
    nav_list: list[NavList] | None = Field(None, alias="navList")
    config: Config | None
    domains: dict[str, str] | None
    download_link: BizContextDownloadLink | None = Field(None, alias="downloadLink")
    device_limit_register_expired: bool | None = Field(None, alias="deviceLimitRegisterExpired")
    subdivisions: list[str] | None
    geo: list[int] | None
    geo_city: GeoCity | None = Field(None, alias="geoCity")
    is_google_bot: bool | None = Field(None, alias="isGoogleBot")
    is_bing_bot: bool | None = Field(None, alias="isBingBot")
    is_bot: bool | None = Field(None, alias="isBot")
    is_search_engine_bot: bool | None = Field(None, alias="isSearchEngineBot")
    is_ttp: bool | None = Field(None, alias="isTTP")
    date_fmt_locale: DateFmtLocale | None = Field(None, alias="dateFmtLocale")
    video_player_config: VideoPlayerConfig | None = Field(None, alias="videoPlayerConfig")
    playback_normalize_path: PlaybackNormalizePath | None = Field(None, alias="playbackNormalizePath")
    bitrate_config: BitrateConfig | None = Field(None, alias="bitrateConfig")
    search_video_for_loggedin: bool | None = Field(None, alias="searchVideoForLoggedin")
    studio_download_entrance: StudioDownloadEntrance | None = Field(None, alias="studioDownloadEntrance")
    live_suggest_config: LiveSuggestConfig | None = Field(None, alias="liveSuggestConfig")
    live_center_config: LiveCenterConfig | None = Field(None, alias="liveCenterConfig")
    live_studio_enable: bool | None = Field(None, alias="liveStudioEnable")
    xgplayer_init_host: XgplayerInitHost | None = Field(None, alias="xgplayerInitHost")
    video_order: BizContextVideoOrder | None = Field(None, alias="videoOrder")


class ItemModule(BaseModel):
    id: str | None
    desc: str | None
    create_time: int | None = Field(None, alias="createTime")
    schedule_time: int | None = Field(None, alias="scheduleTime")
    video: Video | None
    author: str | None
    music: Music | None
    challenges: list[Challenge] | None
    stats: ItemModuleStats | None
    duet_info: DuetInfo | None = Field(None, alias="duetInfo")
    warn_info: list | None = Field(None, alias="warnInfo")
    original_item: bool | None = Field(None, alias="originalItem")
    offical_item: bool | None = Field(None, alias="officalItem")
    text_extra: list[TextExtra] | None = Field(None, alias="textExtra")
    secret: bool | None
    for_friend: bool | None = Field(None, alias="forFriend")
    digged: bool | None
    item_comment_status: int | None = Field(None, alias="itemCommentStatus")
    show_not_pass: bool | None = Field(None, alias="showNotPass")
    vl1: bool | None
    take_down: int | None = Field(None, alias="takeDown")
    item_mute: bool | None = Field(None, alias="itemMute")
    effect_stickers: list[EffectSticker] | None = Field(None, alias="effectStickers")
    author_stats: AuthorStats | None = Field(None, alias="authorStats")
    private_item: bool | None = Field(None, alias="privateItem")
    duet_enabled: bool | None = Field(None, alias="duetEnabled")
    stitch_enabled: bool | None = Field(None, alias="stitchEnabled")
    stickers_on_item: list[StickersOnItem] | None = Field(None, alias="stickersOnItem")
    is_ad: bool | None = Field(None, alias="isAd")
    share_enabled: bool | None = Field(None, alias="shareEnabled")
    comments: list | None
    duet_display: int | None = Field(None, alias="duetDisplay")
    stitch_display: int | None = Field(None, alias="stitchDisplay")
    index_enabled: bool | None = Field(None, alias="indexEnabled")
    ad_authorization: bool | None = Field(None, alias="adAuthorization")
    ad_label_version: int | None = Field(None, alias="adLabelVersion")
    location_created: str | None = Field(None, alias="locationCreated")
    ba_info: str | None = Field(None, alias="BAInfo")
    nickname: str | None
    author_id: str | None = Field(None, alias="authorId")
    author_sec_id: str | None = Field(None, alias="authorSecId")
    avatar_thumb: str | None = Field(None, alias="avatarThumb")
    download_setting: int | None = Field(None, alias="downloadSetting")
    author_private: bool | None = Field(None, alias="authorPrivate")


class SEO(BaseModel):
    meta_params: MetaParams | None = Field(None, alias="metaParams")
    jsonld_list: list[list[JsonldListElement]] | None = Field(None, alias="jsonldList")
    abtest: Abtest | None
    loading: bool | None
    canonical: str | None
    page_type: int | None = Field(None, alias="pageType")
    launch_mode: str | None = Field(None, alias="launchMode")
    directory_config: DirectoryConfig | None = Field(None, alias="directoryConfig")


class UserModule(BaseModel):
    users: dict[str, UserModuleItem] | None
    stats: dict[str, AuthorStats] | None


class AppContext(BaseModel):
    app_context: AppContextClass | None = Field(None, alias="appContext")
    initialized: bool | None
    lang: str | None
    side_nav_active: bool | None = Field(None, alias="sideNavActive")
    is_downgraded_to_csr: bool | None = Field(None, alias="isDowngradedToCSR")


class BizContext(BaseModel):
    biz_context: BizContextClass | None = Field(None, alias="bizContext")
    initialized: bool | None


class TikTokSigiStateRaw(BaseModel):
    app_context: AppContext | None = Field(None, alias="AppContext")
    biz_context: BizContext | None = Field(None, alias="BizContext")
    seo: SEO | None = Field(None, alias="SEO")
    sharing_meta: SharingMeta | None = Field(None, alias="SharingMeta")
    item_list: ItemList | None = Field(None, alias="ItemList")
    item_module: dict[str, ItemModule] | None = Field(None, alias="ItemModule", description="Video items here")
    user_module: UserModule | None = Field(None, alias="UserModule")
    user_page: UserPage | None = Field(None, alias="UserPage")
    recommend_user_list: RecommendUserList | None = Field(None, alias="RecommendUserList")
