# generated by datamodel-codegen:
#   timestamp: 2023-01-19T20:21:50+00:00


from __future__ import annotations

from typing import Any

from melanie import BaseModel, Field, str


class LivingstoneSouthernWhiteFacedOwl(BaseModel):
    uri: str | None
    url_list: list[str] | None
    width: int | None
    height: int | None
    data_size: int | None


class MatchedFriend(BaseModel):
    video_items: Any | None


class AuthorShareInfo(BaseModel):
    share_url: str | None
    share_desc: str | None
    share_title: str | None
    share_qrcode_url: LivingstoneSouthernWhiteFacedOwl | None
    share_title_myself: str | None
    share_title_other: str | None
    share_desc_info: str | None
    now_invitation_card_image_urls: Any | None


class DownloadGeneral(BaseModel):
    code: int | None
    show_type: int | None
    transcode: int | None
    mute: bool | None


class ChaListShareInfo(BaseModel):
    share_url: str | None
    share_desc: str | None
    share_title: str | None
    bool_persist: int | None
    share_title_myself: str | None
    share_title_other: str | None
    share_signature_url: str | None
    share_signature_desc: str | None
    share_quote: str | None
    share_desc_info: str | None
    now_invitation_card_image_urls: Any | None
    share_link_desc: str | None
    whatsapp_desc: str | None


class TextStickerInfo(BaseModel):
    text_size: int | None
    text_color: str | None
    bg_color: str | None
    text_language: str | None
    alignment: int | None
    source_width: float | None
    source_height: float | None


class MatchedPgcSound(BaseModel):
    author: str | None
    title: str | None
    mixed_title: str | None
    mixed_author: str | None


class TextExtra(BaseModel):
    start: int | None
    end: int | None
    type: int | None
    hashtag_name: str | None
    is_commerce: bool | None
    sub_type: int | None
    line_idx: int | None
    tag_id: int | None
    user_id: str | None
    hashtag_id: str | None


class PlaylistInfo(BaseModel):
    mix_id: str | None
    name: str | None
    index: int | None
    item_total: int | None


class RiskInfos(BaseModel):
    vote: bool | None
    warn: bool | None
    risk_sink: bool | None
    type: int | None
    content: str | None


class Statistics(BaseModel):
    aweme_id: str | None
    comment_count: int | None
    digg_count: int | None
    download_count: int | None
    play_count: int | None
    share_count: int | None
    forward_count: int | None
    lose_count: int | None
    lose_comment_count: int | None
    whatsapp_share_count: int | None
    collect_count: int | None


class Status(BaseModel):
    aweme_id: str | None
    is_delete: bool | None
    allow_share: bool | None
    allow_comment: bool | None
    is_private: bool | None
    with_goods: bool | None
    private_status: int | None
    in_reviewing: bool | None
    reviewed: int | None
    self_see: bool | None
    is_prohibited: bool | None
    download_status: int | None


class PlayAddr(BaseModel):
    uri: str | None
    url_list: list[str] | None
    width: int | None
    height: int | None
    url_key: str | None
    data_size: int | None
    file_hash: str | None


class CaptionInfo(BaseModel):
    lang: str | None
    language_id: int | None
    url: str | None
    expire: int | None
    caption_format: str | None
    complaint_id: int | None
    is_auto_generated: bool | None
    sub_id: int | None
    sub_version: int | None
    cla_subtitle_id: int | None
    translator_id: int | None
    language_code: str | None


class OriginalLanguageInfo(BaseModel):
    lang: str | None
    language_id: int | None
    language_code: str | None
    can_translate_realtime: bool | None


class VideoControl(BaseModel):
    allow_download: bool | None
    share_type: int | None
    show_progress_bar: int | None
    draft_progress_bar: int | None
    allow_duet: bool | None
    allow_react: bool | None
    prevent_download_type: int | None
    allow_dynamic_wallpaper: bool | None
    timer_status: int | None
    allow_music: bool | None
    allow_stitch: bool | None


class VideoReplyInfo(BaseModel):
    aweme_id: int | None
    comment_id: int | None
    alias_comment_id: int | None
    user_name: str | None
    comment_msg: str | None
    comment_user_id: int | None
    user_avatar: LivingstoneSouthernWhiteFacedOwl | None
    collect_stat: int | None


class Extra(BaseModel):
    now: int | None
    fatal_item_ids: Any | None


class LogPb(BaseModel):
    impr_id: str | None


class Author(BaseModel):
    uid: str | None
    short_id: int | None
    nickname: str | None
    signature: str | None
    avatar_thumb: LivingstoneSouthernWhiteFacedOwl | None
    avatar_medium: LivingstoneSouthernWhiteFacedOwl | None
    follow_status: int | None
    is_block: bool | None
    custom_verify: str | None
    unique_id: str | None
    room_id: int | None
    authority_status: int | None
    verify_info: str | None
    share_info: AuthorShareInfo | None
    with_commerce_entry: bool | None
    verification_type: int | None
    enterprise_verify_reason: str | None
    is_ad_fake: bool | None
    followers_detail: Any | None
    region: str | None
    commerce_user_level: int | None
    platform_sync_info: Any | None
    is_discipline_member: bool | None
    secret: int | None
    prevent_download: bool | None
    geofencing: Any | None
    video_icon: LivingstoneSouthernWhiteFacedOwl | None
    follower_status: int | None
    comment_setting: int | None
    duet_setting: int | None
    download_setting: int | None
    cover_url: list[LivingstoneSouthernWhiteFacedOwl] | None
    language: str | None
    item_list: Any | None
    is_star: bool | None
    type_label: list | None
    ad_cover_url: Any | None
    comment_filter_status: int | None
    avatar_168x168: LivingstoneSouthernWhiteFacedOwl | None
    avatar_300x300: LivingstoneSouthernWhiteFacedOwl | None
    relative_users: Any | None
    cha_list: Any | None

    need_points: Any | None
    homepage_bottom_toast: Any | None
    can_set_geofencing: Any | None
    white_cover_url: Any | None
    user_tags: Any | None
    bold_fields: Any | None
    search_highlight: Any | None
    mutual_relation_avatars: Any | None
    events: Any | None
    matched_friend: MatchedFriend | None
    advance_feature_item_order: Any | None
    advanced_feature_info: Any | None
    user_profile_guide: Any | None
    shield_edit_field_info: Any | None
    can_message_follow_status_list: Any | None
    account_labels: Any | None
    social_info: str | None


class AwemeACL(BaseModel):
    download_general: DownloadGeneral | None
    download_mask_panel: DownloadGeneral | None
    share_list_status: int | None
    share_general: DownloadGeneral | None
    platform_list: Any | None


class ChaList(BaseModel):
    cid: str | None
    cha_name: str | None
    desc: str | None
    schema_: str | None = Field(None, alias="schema")
    author: dict[str, Any] | None
    user_count: int | None
    share_info: ChaListShareInfo | None
    connect_music: list | None
    type: int | None
    sub_type: int | None
    is_pgcshow: bool | None
    collect_stat: int | None
    is_challenge: int | None
    view_count: int | None
    is_commerce: bool | None
    hashtag_profile: str | None
    cha_attrs: Any | None
    banner_list: Any | None
    show_items: Any | None
    search_highlight: Any | None


class InteractionSticker(BaseModel):
    type: int | None
    index: int | None
    track_info: str | None
    attr: str | None
    text_info: str | None
    text_sticker_info: TextStickerInfo | None


class Music(BaseModel):
    id: int | None
    id_str: str | None
    title: str | None
    author: str | None
    album: str | None
    cover_hd: LivingstoneSouthernWhiteFacedOwl | None
    cover_large: LivingstoneSouthernWhiteFacedOwl | None
    cover_medium: LivingstoneSouthernWhiteFacedOwl | None
    cover_thumb: LivingstoneSouthernWhiteFacedOwl | None
    play_url: LivingstoneSouthernWhiteFacedOwl | None
    schema_url: str | None
    source_platform: int | None
    start_time: int | None
    end_time: int | None
    duration: int | None
    extra: str | None
    user_count: int | None
    position: Any | None
    collect_stat: int | None
    status: int | None
    offline_desc: str | None
    owner_id: str | None
    owner_nickname: str | None
    is_original: bool | None
    mid: str | None
    binded_challenge_id: int | None
    redirect: bool | None
    is_restricted: bool | None
    author_deleted: bool | None
    is_del_video: bool | None
    is_video_self_see: bool | None
    owner_handle: str | None
    author_position: Any | None
    prevent_download: bool | None
    prevent_item_download_status: int | None
    external_song_info: list | None
    avatar_thumb: LivingstoneSouthernWhiteFacedOwl | None
    avatar_medium: LivingstoneSouthernWhiteFacedOwl | None
    avatar_large: LivingstoneSouthernWhiteFacedOwl | None
    preview_start_time: int | None
    preview_end_time: int | None
    is_commerce_music: bool | None
    is_original_sound: bool | None
    artists: Any | None
    lyric_short_position: Any | None
    mute_share: bool | None
    tag_list: Any | None
    is_author_artist: bool | None
    is_pgc: bool | None
    search_highlight: Any | None
    multi_bit_rate_play_info: Any | None
    strong_beat_url: LivingstoneSouthernWhiteFacedOwl | None
    matched_pgc_sound: MatchedPgcSound | None


class OriginalClientText(BaseModel):
    markup_text: str | None
    text_extra: list[TextExtra] | None


class BitRate(BaseModel):
    gear_name: str | None
    quality_type: int | None
    bit_rate: int | None
    play_addr: PlayAddr | None
    is_bytevc1: int | None
    dub_infos: Any | None
    hdr_type: str | None = Field(None, alias="HDR_type")
    hdr_bit: str | None = Field(None, alias="HDR_bit")


class ClaInfo(BaseModel):
    has_original_audio: int | None
    enable_auto_caption: int | None
    original_language_info: OriginalLanguageInfo | None
    caption_infos: list[CaptionInfo] | None
    vertical_positions: Any | None
    hide_original_caption: bool | None


class Video(BaseModel):
    play_addr: PlayAddr | None
    cover: LivingstoneSouthernWhiteFacedOwl | None
    height: int | None
    width: int | None
    dynamic_cover: LivingstoneSouthernWhiteFacedOwl | None
    origin_cover: LivingstoneSouthernWhiteFacedOwl | None
    ratio: str | None
    download_addr: LivingstoneSouthernWhiteFacedOwl | None
    has_watermark: bool | None
    bit_rate: list[BitRate] | None
    duration: int | None
    play_addr_h264: PlayAddr | None
    cdn_url_expired: int | None
    need_set_token: bool | None
    misc_download_addrs: str | None
    tags: Any | None
    big_thumbs: Any | None
    play_addr_bytevc1: PlayAddr | None
    is_bytevc1: int | None
    meta: str | None
    cla_info: ClaInfo | None
    source_hdr_type: int | None = Field(None, alias="source_HDR_type")


class AwemeList(BaseModel):
    aweme_id: str | None
    desc: str | None
    create_time: int | None
    author: Author | None
    music: Music | None
    cha_list: list[ChaList] | None
    video: Video | None
    share_url: str | None
    user_digged: int | None
    statistics: Statistics | None
    status: Status | None
    rate: int | None
    text_extra: list[TextExtra] | None
    is_top: int | None
    label_top: LivingstoneSouthernWhiteFacedOwl | None
    share_info: ChaListShareInfo | None
    distance: str | None
    video_labels: list | None
    is_vr: bool | None
    is_ads: bool | None
    aweme_type: int | None
    cmt_swt: bool | None
    image_infos: Any | None
    risk_infos: RiskInfos | None
    is_relieve: bool | None
    sort_label: str | None
    position: Any | None
    uniqid_position: Any | None
    author_user_id: int | None
    bodydance_score: int | None
    geofencing: Any | None
    is_hash_tag: int | None
    is_pgcshow: bool | None
    region: str | None
    video_text: list | None
    collect_stat: int | None
    label_top_text: Any | None
    group_id: str | None
    prevent_download: bool | None
    nickname_position: Any | None
    challenge_position: Any | None
    item_comment_settings: int | None
    with_promotional_music: bool | None
    long_video: Any | None
    item_duet: int | None
    item_react: int | None
    desc_language: str | None
    interaction_stickers: list[InteractionSticker] | None
    misc_info: str | None
    origin_comment_ids: Any | None
    commerce_config_data: Any | None
    distribute_type: int | None
    video_control: VideoControl | None
    has_vs_entry: bool | None
    need_vs_entry: bool | None
    anchors: Any | None
    hybrid_label: Any | None
    with_survey: bool | None
    geofencing_regions: Any | None
    aweme_acl: AwemeACL | None
    cover_labels: Any | None
    mask_infos: list | None
    search_highlight: Any | None
    playlist_blocked: bool | None
    green_screen_materials: Any | None
    question_list: Any | None
    content_desc: str | None
    content_desc_extra: list | None
    products_info: Any | None
    follow_up_publish_from_id: int | None
    disable_search_trending_bar: bool | None
    music_begin_time_in_ms: int | None
    music_end_time_in_ms: int | None
    item_distribute_source: str | None
    item_source_category: int | None
    branded_content_accounts: Any | None
    is_description_translatable: bool | None
    follow_up_item_id_groups: str | None
    is_text_sticker_translatable: bool | None
    text_sticker_major_lang: str | None
    original_client_text: OriginalClientText | None
    music_selected_from: str | None
    tts_voice_ids: Any | None
    reference_tts_voice_ids: Any | None
    voice_filter_ids: Any | None
    reference_voice_filter_ids: Any | None
    music_title_style: int | None
    video_reply_info: VideoReplyInfo | None
    playlist_info: PlaylistInfo | None
    follow_up_first_item_id: str | None


class TikTokAwemeRaw2(BaseModel):
    status_code: int | None
    min_cursor: int | None
    max_cursor: int | None
    has_more: int | None
    aweme_list: list[AwemeList] | None
    home_model: int | None
    refresh_clear: int | None
    extra: Extra | None
    log_pb: LogPb | None
    preload_ads: list | None
    preload_awemes: Any | None
