# generated by datamodel-codegen:
#   timestamp: 2022-09-15T21:33:33+00:00


from __future__ import annotations

from fastapi_utils.enums import StrEnum
from pydantic import HttpUrl  # noqa

from melanie import BaseModel, constr


class TTSFormatOptions(StrEnum):
    mp3 = "mp3"
    ogg = "ogg"


class Speakers(StrEnum):
    en_US_Ana = "en-US-Ana"
    en_US_Amber = "en-US-Amber"
    en_US_Aria = "en-US-Aria"
    en_US_Ashley = "en-US-Ashley"
    en_US_Brandon = "en-US-Brandon"
    en_US_Christopher = "en-US-Christopher"
    en_US_Cora = "en-US-Cora"
    en_US_Davis = "en-US-Davis"
    en_US_Elizabeth = "en-US-Elizabeth"
    en_US_Eric = "en-US-Eric"
    en_US_Guy = "en-US-Guy"
    en_US_Jacob = "en-US-Jacob"
    en_US_Jane = "en-US-Jane"
    en_US_Jason = "en-US-Jason"
    en_US_Jenny = "en-US-Jenny"
    en_US_Michelle = "en-US-Michelle"
    en_US_Monica = "en-US-Monica"
    en_US_Nancy = "en-US-Nancy"
    en_US_Sara = "en-US-Sara"
    en_US_Tony = "en-US-Tony"
    en_GB_Maisie = "en-GB-Maisie"
    en_GB_Abbi = "en-GB-Abbi"
    en_IN_Prabhat = "en-IN-Prabhat"
    en_AU_Tim = "en-AU-Tim"


class TTSTranslationRequest(BaseModel):
    text: constr(min_length=2, max_length=6000)
    speaker_name: Speakers


class TTSResult(BaseModel):
    url: HttpUrl


class STTJob(BaseModel):
    url: HttpUrl
    headers: dict[str, str]
    endpoint: str
    limit: int = 30
