# generated by datamodel-codegen:
#   timestamp: 2022-09-23T12:45:38+00:00


from __future__ import annotations

from melanie import BaseModel


class APIAuditEvent(BaseModel):
    method: str | None
    duration: float | None
    time: float | None
    ts: str | None
    path: str | None
    url: str | None


class RouteStatsModels(BaseModel):
    route: str
    count: int
    avg_latency: float

    data: list[APIAuditEvent] | None


class APIUsageStatsModel(BaseModel):
    username: str
    routes: dict[str, RouteStatsModels] = {}
