# generated by datamodel-codegen:
#   timestamp: 2023-05-04T15:49:44+00:00

from __future__ import annotations

from datetime import datetime  # noqa

from melanie import BaseModel, Field


class Instrumentation(BaseModel):
    field_type: str | None = Field(None, alias="_type")


class QueryContext(BaseModel):
    original_query: str | None
    alteration_display_query: str | None
    alteration_override_query: str | None
    alteration_method: str | None
    alteration_type: str | None


class Creator(BaseModel):
    name: str | None


class Thumbnail(BaseModel):
    width: int | None
    height: int | None


class VideoObject(BaseModel):
    creator: Creator | None
    duration: str | None
    embed_html: str | None
    allow_https_embed: bool | None
    video_id: str | None
    allow_mobile_embed: bool | None


class InsightsMetadata(BaseModel):
    pages_including_count: int | None
    available_sizes_count: int | None
    recipe_sources_count: int | None
    video_object: VideoObject | None


class Value(BaseModel):
    web_search_url: str | None
    name: str | None
    site_name: str | None
    desc: str | None
    title: str | None
    thumbnail_url: str | None
    date_published: datetime | None
    is_family_friendly: bool | None
    content_url: str | None
    host_page_url: str | None
    content_size: str | None
    encoding_format: str | None
    host_page_display_url: str | None
    width: int | None
    height: int | None
    host_page_fav_icon_url: str | None
    host_page_domain_friendly_name: str | None
    host_page_discovered_date: datetime | None
    thumbnail: Thumbnail | None
    image_insights_token: str | None
    insights_metadata: InsightsMetadata | None
    image_id: str | None
    accent_color: str | None


class AzureWebImageResults(BaseModel):
    web_search_url: str | None
    total_estimated_matches: int | None
    value: list[Value] | None
